/* symbols.h -- Symbol tables for input file type with tokens */
/*   "IM_" prefix avoids conflict with other constants in NPSNET */

struct symbol AnimationSymtab[] = {
   {"ANIMATION_DEF", ANIMATION_DEF, 3},
   {"PFSEQ_CYCLE", SEQ_CYCLE, 7},
   {"PFSEQ_SWING", SEQ_SWING, 7},
   {"BB_SEQ", BB_SEQ, 3},
   {"MODEL_SEQ", MODEL_SEQ, 3},
   {NULL, 0, 0}			/* Terminator */
};

struct symbol BlinkingSymtab[] = {
   {"LIGHT", LIGHT, 3},
   {NULL, 0, 0}			/* Terminator */
};

struct symbol FilterSymtab[] = {
   {"BLOCK_ESPDU", BLOCK_ESPDU, 3},
   {"FORCE_APPEARANCE", FORCE_APPEARANCE, 3},
   {NULL, 0, 0}			/* Terminator */
};

struct symbol LandmarkSymtab[] = {
   {"LANDMARK_ICON", LANDMARK_ICON, 3},
   {NULL, 0, 0}			/* Terminator */
};

struct symbol LocationSymtab[] = {
   {"MODEL_DEF", MODEL_DEF1, 6},
   {"POSITION", IM_POSITION, 3},
   {NULL, 0, 0}			/* Terminator */
};

struct symbol ModelSymtab[] = {
   {"MODEL_DEF", MODEL_DEF2, 6},
   {"JACK_DEF", JACK_DEF, 6},
   {"WEAPON_DEF", WEAPON_DEF, 0},
   {"JADE_DEF", JADE_DEF, 3},
   {"DUDE_DEF", DUDE_DEF, 3},
   {"DIGUY_DEF", DIGUY_DEF, 0},
   {NULL, 0, 0}			/* Terminator */
};

struct symbol NetworkSymtab[] = {
   {"HOST", IM_HOST, 3},
   {NULL, 0, 0}			/* Terminator */
};

struct symbol RadarIconsSymtab[] = {
   {"RADAR_ICON", RADAR_ICON, 3},
   {NULL, 0, 0}			/* Terminator */
};

struct symbol RoundWorldSymtab[] = {
   {"UTM_MAP", UTM_MAP, 3},
   {NULL, 0, 0}			/* Terminator */
};

struct symbol SoundsSymtab[] = {
   {"SOUND_DEF", SOUND_DEF, 3},
   {NULL, 0, 0}			/* Terminator */
};

struct symbol TerrainSymtab[] = {
   {"ON", IM_ON, 0},
   {"OFF", IM_OFF, 0},
   {"MODEL_DEF", MODEL_DEF3, 3},
      {"BRIDGE_MASK", BRIDGE_MASK, 7},
      {"FOLIAGE_MASK", FOLIAGE_MASK, 8},
      {"TERRAIN_MASK", TERRAIN_MASK, 8},
      {"TUNNEL_MASK", TUNNEL_MASK, 7},
      {"WATER_MASK", WATER_MASK, 6},
   {"DB_PAGING", DB_PAGING, 8},
   {"FLAT_WORLD", FLAT_WORLD, 10},
   {NULL, 0, 0}			/* Terminator */
};

struct symbol TransportSymtab[] = {
   {"LOCATION", LOCATION, 3},
   {NULL, 0, 0}			/* Terminator */
};

struct symbol MasterConfSymtab[] = {
/* Don't change the order in here! */
   /* misc */
   {"ON", IM_ON, 0},
   {"OFF", IM_OFF, 0},
   {"EMPTY", IM_EMPTY, 3},
   {"NONE", IM_NONE, 3},
   /* these must precede shorter potential matches */
   {"FCS_CHECK", FCS_CHECK, 5},
   {"FCS_PORT", FCS_PORT, 6},
   {"FCS_PROMPT", FCS_PROMPT, 6},
   {"FCS_MP", FCS_MP, 6},
   {"MULTICAST_GROUP", MULTICAST_GROUP, 11},
   {"MULTICAST_TTL", MULTICAST_TTL, 11},
   {"WINDOW_SIZE", WINDOW_SIZE, 7},
   /* commands */
   {"ANIMATIONS", ANIMATIONS, 0},
   {"AUTO_FILE", AUTO_FILE, 6},
   {"AUTO_STATE", AUTO_STATE, 6},
   {"ANIMATION_FILE", ANIMATION_FILE, 10},
   {"BDIHML", BDIHML, 6},
   {"DIGUY_SPEED_RATIO", DIGUY_SPEED_RATIO, 7},
   {"DIGUY_POSITION_ERROR", DIGUY_POSITION_ERROR, 18},
   {"DIGUY_TIME_CONSTANT", DIGUY_TIME_CONSTANT, 8},
   {"DIGUY_TRANS_SMOOTHNESS", DIGUY_TRANS_SMOOTHNESS, 8},
      {"TRANS_IMMEDIATE", TRANS_IMMEDIATE, 9},
      {"IMMEDIATE_TRANS", IMMEDIATE_TRANS, 9},
      {"TRANS_SMOOTHEST", TRANS_SMOOTHEST, 9},
   {"DIGUY_POSITION_MODE", DIGUY_POSITION_MODE, 18},
      {"SMOOTH_MODE", SMOOTH_MODE, 6},
      {"PRECISE_MODE", PRECISE_MODE, 7},
   {"DIGUY_POSITION_MECHANISM", DIGUY_POSITION_MECHANISM, 18},
      {"DIGUY_INTERNAL", DIGUY_INTERNAL, 9},
      {"NPSNET_INTERNAL", NPSNET_INTERNAL, 10},
   {"BLINKING_LIGHTS_FILE", BLINKING_LIGHTS_FILE, 3},
   {"BOUNDING_BOX", IM_BOUNDING_BOX, 3},
   {"C2_FILE", C2_FILE, 3},
   {"CHANNEL", CHANNEL, 3},
   {"CLIP_PLANES", CLIP_PLANES, 3},
   {"CONTROL", IM_CONTROL, 3},
      {"FCS", FCS, 3},
      {"FLYBOXIN", FLYBOXIN, 7},
      {"LEATHER_FLYBOX", LEATHER_FLYBOX, 0},
      {"KAFLIGHT", KAFLIGHT, 3},
      {"KEYBOARD", KEYBOARD, 3},
      {"PAD", KEYBOARD, 0},
      {"SPACEBALL", SPACEBALL, 3},
      {"BALL", SPACEBALL, 3},
      {"DRIVE", SPACEBALL, 3},
      {"SHIP_PANEL", SHIP_PANEL, 3},
      {"SUB_PANEL", SUB_PANEL, 3},
      {"AUSA_ODT", AUSA_ODT, 5},
   {"CPU_LOCK", CPU_LOCK, 3},
   {"CURSOR_FILE", CURSOR_FILE, 8},
   {"DB_OFFSET", DB_OFFSET, 5},
   {"DB_PAGES_ALLOWED", DB_PAGES_ALLOWED, 8},
   {"DB_TSG_FILE", DB_TSG_FILE, 6},
   {"DEAD_SWITCH", DEAD_SWITCH, 4},
   {"DIS_EXERCISE", DIS_EXERCISE, 7},
   {"DIS_ENUM", DIS_ENUM, 7},
      {"DISv203", DISv203, 7},
      {"DISv204", DISv204, 7},
   {"DIS_HEARTBEAT", DIS_HEARTBEAT, 5},
   {"DIS_POSDELTA", DIS_POSDELTA, 5},
   {"DIS_ROTDELTA", DIS_ROTDELTA, 5},
   {"DIS_TIME_OUT", DIS_TIME_OUT, 5},
   {"DUMP_FILE", DUMP_FILE, 3},
   {"DVW_PATHS", DVW_PATHS, 3},
   {"DYNAMIC_OBJS", DYNAMIC_OBJS, 3},
   {"EARTH_SKY_MODE", EARTH_SKY_MODE, 3},
      {"FAST", FAST, 3},
      {"TAG", TAG, 3},
      {"SKY_GROUND", SKY_GROUND, 5},
      {"SKY_CLEAR", SKY_CLEAR, 5},
      {"SKY", SKY, 3},
   {"ENVIRONMENTAL", ENVIRONMENTAL, 3},
   {"ENTITY_FILE", ENTITY_FILE, 3},
   {"ETHER_INTERF", ETHER_INTERF, 3},
   {"EXERCISE", DIS_EXERCISE, 3},
   {"FIELD_OF_VIEW", FOV, 3},
   {"FILTER_FILE", FILTER_FILE, 3},
   {"FLYBOX_PORT", FLYBOX_PORT, 7},
   {"FLYBOX", FLYBOX, 3},
   {"FOG", FOG, 0},
   {"FOG_TYPE", FOG_TYPE, 0},
      {"FOG_VTX_LIN", FOG_VTX_LIN, 0},
      {"FOG_VTX_EXP", FOG_VTX_EXP, 0},
      {"FOG_VTX_EXP2", FOG_VTX_EXP2, 0},
      {"FOG_PIX_LIN", FOG_PIX_LIN, 0},
      {"FOG_PIX_EXP", FOG_PIX_EXP, 0},
      {"FOG_PIX_EXP2", FOG_PIX_EXP2, 0},
      {"FOG_PIX_SPLINE", FOG_PIX_SPLINE, 0},
   {"FOG_NEAR", FOG_NEAR, 0},
   {"FOG_FAR", FOG_FAR, 0},
   {"FORCE", FORCE, 3},
      {"BLUE", IM_BLUE, 3},
      {"RED", IM_RED, 3},
      {"WHITE", IM_WHITE, 5},
      {"OTHER", IM_OTHER, 3},
   {"FOV", FOV, 3},
   {"FRAME_RATE", IM_FRAME_RATE, 3},
   {"FS_CONFIG", FS_CONFIG, 4},
   {"FS_PORT", FS_PORT, 4},
   {"FS_SCALE", FS_SCALE, 0},
   {"GROUND_HEIGHT", GROUND_HEIGHT, 3},
   {"HEAD_MOUNTED_DISPLAY", HMD, 3},
   {"HIRES", HIRES, 3},
      {"NET_OFF", IM_NET_OFF, 0},
      {"RECEIVE_ONLY", RECEIVE_ONLY, 3},
      {"SEND_ONLY", SEND_ONLY, 6},
      {"SEND_AND_RECEIVE", SEND_AND_RECEIVE, 6},
   {"HMD", HMD, 0},
   {"HMD_FILE", HMD_FILE, 4},
   {"HORIZON_ANGLE", HORIZON_ANGLE, 3},
   {"HUD_FONT_FILE", HUD_FONT_FILE, 5},
   {"HUD_LEVEL", HUD_LEVEL, 5},
   {"IDENTIFY_FILE", IDENTIFY_FILE, 3},
   {"INTRO_FONT_FILE", INTRO_FONT_FILE, 3},
   {"JACK", IM_JACK, 4},
   {"LANDMARK_FILE", LANDMARK_FILE, 3},
   {"LEATHER_FLYBOX_CHECK", LEATHER_FLYBOX_CHECK, 16},
   {"LEATHER_FLYBOX_PORT", LEATHER_FLYBOX_PORT, 16},
   {"LOCATION_FILE", LOCATION_FILE, 4},
   {"LOD_FADE", LOD_FADE, 5},
   {"LOD_SCALE", LOD_SCALE, 5},
   {"LW_RECEIVE_PORT", LW_RECEIVE_PORT, 5},
   {"LW_SEND_PORT", LW_SEND_PORT, 5},
   {"LW_MACHINE_NAME", LW_MACHINE_NAME, 5},
   {"MARKING", MARKING, 4},
   {"MASTER", MASTER, 3},
   {"MAX_ALTITUDE", IM_MAX_ALTITUDE, 7},
   {"MODEL_FILE", MODEL_FILE, 4},
   {"MODSAF_MAP", MODSAF_MAP, 4},
   {"MULTICAST", MULTICAST, 6},
   {"MULTISAMPLE", MULTISAMPLE, 6},
   {"NETWORKING", NETWORKING, 8},
   {"NETWORK_FILE", NETWORK_FILE, 8},
   {"NOTIFY_LEVEL", NOTIFY_LEVEL, 5},
      {"FATAL", IM_FATAL, 3},
      {"WARN", WARN, 3},
      {"NOTICE", NOTICE, 5},
      {"INFO", INFO, 3},
      {"DEBUG", IM_DEBUG, 3},
      {"FPDEBUG", FPDEBUG, 3},
   {"NPS_PIC_DIR", NPS_PIC_DIR, 3},
   {"ODT_MP", ODT_MP, 6},
   {"ODT_PORT", ODT_PORT, 6},
   {"PANEL_GROUP", PANEL_GROUP, 7},
   {"PANEL_TTL", PANEL_TTL, 7},
   {"PANEL_PORT", PANEL_PORT, 7},
   {"PDUPOSITION", PDUPOSITION, 3},
   {"PHASE", PHASE, 3},
      {"FREE", ALG_FREE, 3},
      {"FLOAT", ALG_FLOAT, 3},
      {"LOCK", ALG_LOCK, 4},
   {"PICTURES", PICTURES, 3},
   {"PIPE", PIPE, 3},
   {"PO_CTDB_FILE", PO_CTDB_FILE, 4},
   {"PO_DATABASE", IM_PO_DATABASE, 4},
   {"PO_EXERCISE", IM_PO_EXERCISE, 4},
   {"PO_PORT", IM_PO_PORT, 4},
   {"PORT", IM_PORT, 3},
   {"PROCESS_MODE", PROCESS_MODE, 3},
      {"APPCULLDRAW", APPCULLDRAW, 9},
      {"APP_CULLDRAW", APP_CULLDRAW, 9},
      {"APPCULL_DRAW", APPCULL_DRAW, 9},
      {"APP_CULL_DRAW", APP_CULL_DRAW, 9},
      {"DEFAULT", IM_DEFAULT, 7},
   {"RADAR_ICON_FILE", RADAR_ICON_FILE, 3},
   {"RANGE_FILTER", RANGE_FILTER, 5},
   {"REMOTE_INPUT_PANEL", REMOTE_INPUT_PANEL, 3},
   {"ROAD_FILE", ROAD_FILE, 3},
   {"ROUND_WORLD_FILE", ROUND_WORLD_FILE, 3},
   {"SEARCH_PATH", SEARCH_PATH, 3},
   {"SCORING", SCORING, 3},
   {"SOUND_FILE", SOUND_FILE, 6},
   {"SOUND", IM_SOUND, 5},
   {"STATIC_OBJS", STATIC_OBJS, 4},
   {"STEALTH", STEALTH, 4},
   {"STEREO", STEREO, 4},
   {"TARGET_ENTITY", TARGET_ENTITY, 8},
   {"TARGET_BOUNDING_BOX", TARGET_BOUNDING_BOX, 8},
   {"TERRAIN_FILE", IM_TERRAIN_FILE, 3},
   {"TESTPORT", TESTPORT, 3},
   {"TRAKER_FILE", TRAKER_FILE, 8},
   {"TRAKER_PORT", TRAKER_PORT, 8},
   {"TRANSPORT_FILE", TRANSPORT_FILE, 9},
   {"TREADPORT", TREADPORT, 3},
   {"UNIPORT", UNIPORT, 3},
   {"UPPERBODY", UPPERBODY, 3},
   {"USE_ROUND_WORLD", USE_ROUND_WORLD, 9},
   {"VEHICLE_DRIVEN", VEHICLE_DRIVEN, 3},
   {"VIEWPORT", VIEWPORT, 5},
   {"VIEW_HPR", VIEW_HPR, 6},
   {"VIEW_XYZ", VIEW_XYZ, 6},
   {"VIEW", VIEW, 4},
      {"AIRPORT", AIRPORT, 3},
      {"CANYON", CANYON, 3},
      {"VILLAGE", VILLAGE, 3},
      {"PIER", PIER, 3},
      {"START", IM_START, 4},
   {"WAYPOINTS", WAYPOINTS, 3},
   {"WEAPON_VIEW", IM_WEAPON_VIEW, 6},
   {"WINDOW", IM_WINDOW, 0},
      {"CLOSED", CLOSED, 3},
      {"CUSTOM", CUSTOM, 3},
      {"SVGA", SVGA, 3},
      {"FULL", FULL, 3},
      {"NTSC", NTSC, 3},
      {"PAL", PAL, 0},
      {"NORMAL", NORMAL, 3},
      {"VIM", VIM, 0},
      {"THREE_TV", THREE_TV, 7},
      {"THREE_BUNKER", THREE_BUNKER, 7},
      {"TWO_TPORT", TWO_TPORT, 5},
      {"TWO_ADJACENT", TWO_ADJACENT, 5},
      {"FS_MCO", FS_MCO, 7},
      {"FS_ST_BUFFERS", FS_ST_BUFFERS, 7},
   {NULL, 0, 0}			/* Terminator */
};
