
//////////////////////////////////////////////////////////////
//
// Header file for Deck
//
//    This file is generated by RapidApp
//
//    This class is derived from DeckUI which 
//    implements the user interface created in 
//    the interface builder. This class contains virtual
//    functions that are called from the user interface.
//
//    When you modify this header file, limit your changes to adding
//    members below the "//--- End generated code section" markers
//
//    This will allow the builder to integrate changes more easily
//
//    This class is a ViewKit user interface "component".
//    For more information on how components are used, see the
//    "ViewKit Programmers' Manual", and the RapidApp
//    User's Guide.
//////////////////////////////////////////////////////////////
#ifndef DECK_H
#define DECK_H
#include "DeckUI.h"

#include <Vk/VkSimpleWindow.h>
//---- End generated headers


//---- Deck class declaration

class Deck : public DeckUI
{

  public:

    Deck(const char *, Widget);
    Deck(const char *);
    ~Deck();
    const char *  className();
    virtual void setParent(VkSimpleWindow  *);

    //---- End generated code section
    void update();
    void bell_to_port_ind(int);
    void bell_to_stbd_ind(int);

  protected:


    // These functions will be called as a result of callbacks
    // registered in DeckUI

    //virtual void process_voice_cmd( Widget, XtPointer );
    virtual void back_full_order ( Widget, XtPointer );
    virtual void back_one_third_order ( Widget, XtPointer );
    virtual void back_two_third_order ( Widget, XtPointer );
    virtual void flank_order ( Widget, XtPointer );
    virtual void full_order ( Widget, XtPointer );
    virtual void o_rpm_100s_add ( Widget, XtPointer );
    virtual void o_rpm_100s_minus ( Widget, XtPointer );
    virtual void o_rpm_10s_add ( Widget, XtPointer );
    virtual void o_rpm_10s_minus ( Widget, XtPointer );
    virtual void o_rpm_1s_add ( Widget, XtPointer );
    virtual void o_rpm_1s_minus ( Widget, XtPointer );
    virtual void one_third_order ( Widget, XtPointer );
    virtual void process_voice_cmd ( Widget, XtPointer );
    virtual void rudder_angle ( Widget, XtPointer );
    virtual void s_back_full_order ( Widget, XtPointer );
    virtual void s_back_one_third_order ( Widget, XtPointer );
    virtual void s_back_two_third_order ( Widget, XtPointer );
    virtual void s_flank_order ( Widget, XtPointer );
    virtual void s_full_order ( Widget, XtPointer );
    virtual void s_one_third_order ( Widget, XtPointer );
    virtual void s_stnd_order ( Widget, XtPointer );
    virtual void s_stop_order ( Widget, XtPointer );
    virtual void s_two_third_order ( Widget, XtPointer );
    virtual void stnd_order ( Widget, XtPointer );
    virtual void stop_order ( Widget, XtPointer );
    virtual void two_third_order ( Widget, XtPointer );

    VkSimpleWindow * _parent;
    //---- End generated code section


  private:

};
#endif

