
/////////////////////////////////////////////////////////////
//
// Source file for Deck
//
//    This file is generated by RapidApp
//
//    This class is derived from DeckUI which 
//    implements the user interface created in 
//    the interface builder. This class contains virtual
//    functions that are called from the user interface.
//
//    When you modify this source, limit your changes to 
//    modifying the emtpy virtual functions. You can also add
//    new functions below the "//--- End generated code section" markers
//
//    This will allow the builder to integrate changes more easily
//
//    This class is a ViewKit user interface "component".
//    For more information on how components are used, see the
//    "ViewKit Programmers' Manual", and the RapidApp
//    User's Guide.
/////////////////////////////////////////////////////////////

#include "Deck.h"
#include "ShipControlWindowMainWindow.h"
#include <Vk/VkEZ.h>
#include <Sgm/Dial.h> 
#include <Vk/VkCompletionField.h> 
#include <Xm/ArrowB.h> 
#include <Xm/BulletinB.h> 
#include <Xm/Form.h> 
#include <Xm/Frame.h> 
#include <Xm/Label.h> 
#include <Xm/RowColumn.h> 
#include <Xm/Separator.h> 
#include <Xm/TextF.h> 
#include <Xm/ToggleB.h> 
#include <Vk/VkResource.h>
#include <Vk/VkSimpleWindow.h>

#include <Vk/VkFormat.h> 
#include <stdlib.h>
#include <iostream.h>
#include <math.h>
#include <string.h>
#include <ctype.h>
#include <idunetlib.h>
#include <idu.h>      

#define MPS_TO_KTS 1.94f

extern void VkUnimplemented(Widget, const char *);
extern OodToNPSNETIDU       oodidu;
extern NPSNETToShipIDU     *updateshipidu;
extern IDU_net_manager     *net;

///////////////////////////////////////////////////////////////////////////////
// The following non-container widgets are created by DeckUI and are
// available as protected data members inherited by this class
//
//  XmLabel		    _port_ood_label
//  XmLabel		    _stbd_ood_label
//  XmLabel		    _actual_O_course_label1
//  VkCompletionField		    _voice_cmd_textfield
//  XmTextField		    _actual_rudder_textfield
//  XmLabel		    _rudder_label
//  SgDial		    _rudder_dial
//  XmToggleButton		    _o_flank_toggle1
//  XmToggleButton		    _o_full_toggle1
//  XmToggleButton		    _o_stnd_toggle1
//  XmToggleButton		    _o_two_third_toggle1
//  XmToggleButton		    _o_one_third_toggle1
//  XmToggleButton		    _o_stop_toggle1
//  XmToggleButton		    _o_back_one_third_toggle1
//  XmToggleButton		    _o_back_two_third_toggle1
//  XmToggleButton		    _o_backfull_toggle1
//  XmLabel		    _rpm_ood_label
//  XmTextField		    _o_rpm_1s_textfield
//  XmTextField		    _o_rpm_10s_textfield
//  XmTextField		    _o_rpm_100s_textfield
//  XmArrowButton		    _o_rpm_1s_dwn_arrow
//  XmArrowButton		    _o_rpm_10s_dwn_arrow
//  XmArrowButton		    _o_rpm_100s_dwn_arrow
//  XmArrowButton		    _o_rpm_1s_up_arrow
//  XmArrowButton		    _o_rpm_10s_up_arrow
//  XmArrowButton		    _o_rpm_100s_up_arrow
//  XmLabel		    _ood_order_label
//  XmToggleButton		    _o_flank_toggle
//  XmToggleButton		    _o_full_toggle
//  XmToggleButton		    _o_stnd_toggle
//  XmToggleButton		    _o_two_third_toggle
//  XmToggleButton		    _o_one_third_toggle
//  XmToggleButton		    _o_stop_toggle
//  XmToggleButton		    _o_back_one_third_toggle
//  XmToggleButton		    _o_back_two_third_toggle
//  XmToggleButton		    _o_backfull_toggle
//  SgDial		    _compass_dial
//  XmTextField		    _actual_O_speed_textfield
//  XmTextField		    _actual_O_course_textfield
//  XmLabel		    _actual_OOD_label
//  XmSeparator		    _actual_OOD_separator
//  XmLabel		    _actual_O_speed_label
//  XmLabel		    _actual_O_course_label
//
///////////////////////////////////////////////////////////////////////////////


//---- End generated headers


//---- Deck Constructor

Deck::Deck(const char *name, Widget parent) : 
                   DeckUI(name, parent) 
{ 
    // This constructor is called after the component's interface has been built.

    //--- Add application code here:
    show();

} // End Constructor



Deck::Deck(const char *name) : 
                   DeckUI(name) 
 { 
    // This constructor calls DeckUI(name)
    // which does not create any widgets. Usually, this
    // constructor is not used

    //--- Add application code here:


} // End Constructor



Deck::~Deck()
{
    // The base class destructors are responsible for
    // destroying all widgets and objects used in this component.
    // Only additional items created directly in this class
    // need to be freed here.

    //--- Add application destructor code here:


}


const char * Deck::className() // classname
{
    return ("Deck");
} // End className()


//Convert bell orders to appropriate port bell toggle button
void Deck::bell_to_port_ind(int bell)
{
   switch(bell){
      case -3:  //back full bell (-100 rpms)
         XmToggleButtonSetState(_o_backfull_toggle,TRUE,TRUE);
         break;
      case -2:  //back 2/3 bell (-66 rpms)
         XmToggleButtonSetState(_o_back_two_third_toggle,TRUE,TRUE);
         break;
      case -1:  //back 1/3 bell (-33 rpms)
         XmToggleButtonSetState(_o_back_one_third_toggle,TRUE,TRUE);
         break;
      case 0:  //All Stop (0 rpms)
         XmToggleButtonSetState(_o_stop_toggle,TRUE,TRUE);
         break;
      case 1:  //1/3 bell (38 rpms)
         XmToggleButtonSetState(_o_one_third_toggle,TRUE,TRUE);
         break;
      case 2:  //2/3 bell (77 rpms)
         XmToggleButtonSetState(_o_two_third_toggle,TRUE,TRUE);
         break;
      case 3:  //std bell (115 rpms)
         XmToggleButtonSetState(_o_stnd_toggle,TRUE,TRUE);
         break;
      case 4:  //full bell (172 rpms)
         XmToggleButtonSetState(_o_full_toggle,TRUE,TRUE);
         break;
      case 5:  //flk bell (230 rpms)
         XmToggleButtonSetState(_o_flank_toggle,TRUE,TRUE);
         break;
      default:
         break;
   } // end of switch
}


//Convert bell orders to appropriate stbd bell toggle button
void Deck::bell_to_stbd_ind(int bell)
{
   switch(bell){
      case -3:  //back full bell (-100 rpms)
         XmToggleButtonSetState(_o_backfull_toggle1,TRUE,TRUE);
         break;
      case -2:  //back 2/3 bell (-66 rpms)
         XmToggleButtonSetState(_o_back_two_third_toggle1,TRUE,TRUE);
         break;
      case -1:  //back 1/3 bell (-33 rpms)
         XmToggleButtonSetState(_o_back_one_third_toggle1,TRUE,TRUE);
         break;
      case 0:  //All Stop (0 rpms)
         XmToggleButtonSetState(_o_stop_toggle1,TRUE,TRUE);
         break;
      case 1:  //1/3 bell (38 rpms)
         XmToggleButtonSetState(_o_one_third_toggle1,TRUE,TRUE);
         break;
      case 2:  //2/3 bell (77 rpms)
         XmToggleButtonSetState(_o_two_third_toggle1,TRUE,TRUE);
         break;
      case 3:  //std bell (115 rpms)
         XmToggleButtonSetState(_o_stnd_toggle1,TRUE,TRUE);
         break;
      case 4:  //full bell (172 rpms)
         XmToggleButtonSetState(_o_full_toggle1,TRUE,TRUE);
         break;
      case 5:  //flk bell (230 rpms)
         XmToggleButtonSetState(_o_flank_toggle1,TRUE,TRUE);
         break;
      default:
      break;
   } // end of switch
}


void Deck::update() 
{
    //actual course,speed
    XmTextFieldSetString(_actual_O_course_textfield,
                         (char *) VkFormat("%d", (int)updateshipidu->ship_course));
    XmTextFieldSetString(_actual_O_speed_textfield,
      (char *) VkFormat("%d KTS", (int)(updateshipidu->ship_speed*MPS_TO_KTS)));
    EZ(_compass_dial) = (int)updateshipidu->ship_course;
    if (updateshipidu->space_holder) { // Keyboard pressed so update panel
       EZ(_rudder_dial) = 180.0f-(4.5f*updateshipidu->ship_ordered_rudder_angle);
       //oodidu.ood_rudder_angle = (180.0f - (float)EZ(_rudder_dial)) / 4.5f;
       bell_to_port_ind((int)updateshipidu->ship_ordered_port_bell);
       bell_to_stbd_ind((int)updateshipidu->ship_ordered_stbd_bell);
       int rpm = (int)updateshipidu->ship_ordered_rpm;
//cerr<<rpm<<endl;
       int huns = truncf(rpm/100); rpm-=(huns*100);
       int tens = truncf(rpm/10); 
       int ones = rpm-=(tens*10);
       XmTextFieldSetString(_o_rpm_100s_textfield,(char *)VkFormat("%d",huns));
       XmTextFieldSetString(_o_rpm_10s_textfield,(char *)VkFormat("%d",tens));
       XmTextFieldSetString(_o_rpm_1s_textfield,(char *)VkFormat("%d",ones));
    }
} // End update()


void Deck::back_full_order ( Widget w, XtPointer callData )
{
    XmAnyCallbackStruct *cbs = (XmAnyCallbackStruct*) callData;

    //--- Comment out the following line when Deck::back_full_order is implemented:

    //::VkUnimplemented ( w, "Deck::back_full_order" );


    //--- Add application code for Deck::back_full_order here:
    oodidu.ood_port_bell = -3;
    if ( !(net->write_idu((char *)&oodidu,SHIP_Ood_To_NPSNET_Type)) )
             cerr << "ERROR:\tCould not send OOD IDU." << endl;

} // End Deck::back_full_order()


void Deck::back_one_third_order ( Widget w, XtPointer callData )
{
    XmAnyCallbackStruct *cbs = (XmAnyCallbackStruct*) callData;

    //--- Comment out the following line when Deck::back_one_third_order is implemented:

    //::VkUnimplemented ( w, "Deck::back_one_third_order" );


    //--- Add application code for Deck::back_one_third_order here:
    oodidu.ood_port_bell = -1;
    if ( !(net->write_idu((char *)&oodidu,SHIP_Ood_To_NPSNET_Type)) )
             cerr << "ERROR:\tCould not send OOD IDU." << endl;

} // End Deck::back_one_third_order()


void Deck::back_two_third_order ( Widget w, XtPointer callData )
{
    XmAnyCallbackStruct *cbs = (XmAnyCallbackStruct*) callData;

    //--- Comment out the following line when Deck::back_two_third_order is implemented:

    //::VkUnimplemented ( w, "Deck::back_two_third_order" );


    //--- Add application code for Deck::back_two_third_order here:
    oodidu.ood_port_bell = -2;
    if ( !(net->write_idu((char *)&oodidu,SHIP_Ood_To_NPSNET_Type)) )
             cerr << "ERROR:\tCould not send OOD IDU." << endl;

} // End Deck::back_two_third_order()


void Deck::flank_order ( Widget w, XtPointer callData )
{
    XmAnyCallbackStruct *cbs = (XmAnyCallbackStruct*) callData;

    //--- Comment out the following line when Deck::flank_order is implemented:

    //::VkUnimplemented ( w, "Deck::flank_order" );


    //--- Add application code for Deck::flank_order here:
    oodidu.ood_port_bell = 5;
    if ( !(net->write_idu((char *)&oodidu,SHIP_Ood_To_NPSNET_Type)) )
             cerr << "ERROR:\tCould not send OOD IDU." << endl;

} // End Deck::flank_order()


void Deck::full_order ( Widget w, XtPointer callData )
{
    XmAnyCallbackStruct *cbs = (XmAnyCallbackStruct*) callData;

    //--- Comment out the following line when Deck::full_order is implemented:

    //::VkUnimplemented ( w, "Deck::full_order" );


    //--- Add application code for Deck::full_order here:
    oodidu.ood_port_bell = 4;
    if ( !(net->write_idu((char *)&oodidu,SHIP_Ood_To_NPSNET_Type)) )
             cerr << "ERROR:\tCould not send OOD IDU." << endl;

} // End Deck::full_order()


void Deck::o_rpm_100s_add ( Widget w, XtPointer callData )
{
    XmAnyCallbackStruct *cbs = (XmAnyCallbackStruct*) callData;

    //--- Comment out the following line when Deck::o_rpm_100s_add is implemented:

    //::VkUnimplemented ( w, "Deck::o_rpm_100s_add" );


    //--- Add application code for Deck::o_rpm_100s_add here:
    int a = atoi (XmTextFieldGetString(_o_rpm_100s_textfield));
    int b = atoi (XmTextFieldGetString(_o_rpm_10s_textfield));
    int c = atoi (XmTextFieldGetString(_o_rpm_1s_textfield));
    if ( a == 9 )
       a = -1;
    XmTextFieldSetString(_o_rpm_100s_textfield, (char *) VkFormat("%d", a+1));
    oodidu.ood_rpm = ((a+1)*100) + (b*10) + c;
//cerr<<oodidu.ood_rpm<<endl;
    if ( !(net->write_idu((char *)&oodidu,SHIP_Ood_To_NPSNET_Type)) )
             cerr << "ERROR:\tCould not send OOD IDU." << endl;

} // End Deck::o_rpm_100s_add()


void Deck::o_rpm_100s_minus ( Widget w, XtPointer callData )
{
    XmAnyCallbackStruct *cbs = (XmAnyCallbackStruct*) callData;

    //--- Comment out the following line when Deck::o_rpm_100s_minus is implemented:

    //::VkUnimplemented ( w, "Deck::o_rpm_100s_minus" );


    //--- Add application code for Deck::o_rpm_100s_minus here:
    int a = atoi (XmTextFieldGetString(_o_rpm_100s_textfield));
    int b = atoi (XmTextFieldGetString(_o_rpm_10s_textfield));
    int c = atoi (XmTextFieldGetString(_o_rpm_1s_textfield));
    if ( a == 0 )
       a = 10;
    XmTextFieldSetString(_o_rpm_100s_textfield, (char *) VkFormat("%d", a-1));
    oodidu.ood_rpm = ((a-1)*100) + (b*10) + c;
//cerr<<oodidu.ood_rpm<<endl;
    if ( !(net->write_idu((char *)&oodidu,SHIP_Ood_To_NPSNET_Type)) )
             cerr << "ERROR:\tCould not send OOD IDU." << endl;

} // End Deck::o_rpm_100s_minus()


void Deck::o_rpm_10s_add ( Widget w, XtPointer callData )
{
    XmAnyCallbackStruct *cbs = (XmAnyCallbackStruct*) callData;

    //--- Comment out the following line when Deck::o_rpm_10s_add is implemented:

    //::VkUnimplemented ( w, "Deck::o_rpm_10s_add" );


    //--- Add application code for Deck::o_rpm_10s_add here:
    int a = atoi (XmTextFieldGetString(_o_rpm_100s_textfield));
    int b = atoi (XmTextFieldGetString(_o_rpm_10s_textfield));
    int c = atoi (XmTextFieldGetString(_o_rpm_1s_textfield));
    if ( b == 9 )
         b = -1;
    XmTextFieldSetString(_o_rpm_10s_textfield, (char *) VkFormat("%d", b+1));
    oodidu.ood_rpm = (a*100) + ((b+1)*10) + c;
//cerr<<oodidu.ood_rpm<<endl;
    if ( !(net->write_idu((char *)&oodidu,SHIP_Ood_To_NPSNET_Type)) )
             cerr << "ERROR:\tCould not send OOD IDU." << endl;

} // End Deck::o_rpm_10s_add()


void Deck::o_rpm_10s_minus ( Widget w, XtPointer callData )
{
    XmAnyCallbackStruct *cbs = (XmAnyCallbackStruct*) callData;

    //--- Comment out the following line when Deck::o_rpm_10s_minus is implemented:

    //::VkUnimplemented ( w, "Deck::o_rpm_10s_minus" );


    //--- Add application code for Deck::o_rpm_10s_minus here:
    int a = atoi (XmTextFieldGetString(_o_rpm_100s_textfield));
    int b = atoi (XmTextFieldGetString(_o_rpm_10s_textfield));
    int c = atoi (XmTextFieldGetString(_o_rpm_1s_textfield));
    if ( b == 0 )
        b = 10;
    XmTextFieldSetString(_o_rpm_10s_textfield, (char *) VkFormat("%d", b-1));
    oodidu.ood_rpm = (a*100) + ((b-1)*10) + c;
//cerr<<oodidu.ood_rpm<<endl;
    if ( !(net->write_idu((char *)&oodidu,SHIP_Ood_To_NPSNET_Type)) )
             cerr << "ERROR:\tCould not send OOD IDU." << endl;

} // End Deck::o_rpm_10s_minus()


void Deck::o_rpm_1s_add ( Widget w, XtPointer callData )
{
    XmAnyCallbackStruct *cbs = (XmAnyCallbackStruct*) callData;

    //--- Comment out the following line when Deck::o_rpm_1s_add is implemented:

    //::VkUnimplemented ( w, "Deck::o_rpm_1s_add" );


    //--- Add application code for Deck::o_rpm_1s_add here:
    int a = atoi (XmTextFieldGetString(_o_rpm_100s_textfield));
    int b = atoi (XmTextFieldGetString(_o_rpm_10s_textfield));
    int c = atoi (XmTextFieldGetString(_o_rpm_1s_textfield));
    if ( c == 9 )
      c = -1;
    XmTextFieldSetString(_o_rpm_1s_textfield, (char *) VkFormat("%d", c+1));
    oodidu.ood_rpm = (a*100) + (b*10) + c+1;
//cerr<<oodidu.ood_rpm<<endl;
    if ( !(net->write_idu((char *)&oodidu,SHIP_Ood_To_NPSNET_Type)) )
             cerr << "ERROR:\tCould not send OOD IDU." << endl;

} // End Deck::o_rpm_1s_add()


void Deck::o_rpm_1s_minus ( Widget w, XtPointer callData )
{
    XmAnyCallbackStruct *cbs = (XmAnyCallbackStruct*) callData;

    //--- Comment out the following line when Deck::o_rpm_1s_minus is implemented:

    //::VkUnimplemented ( w, "Deck::o_rpm_1s_minus" );


    //--- Add application code for Deck::o_rpm_1s_minus here:
    int a = atoi (XmTextFieldGetString(_o_rpm_100s_textfield));
    int b = atoi (XmTextFieldGetString(_o_rpm_10s_textfield));
    int c = atoi (XmTextFieldGetString(_o_rpm_1s_textfield));
    if ( c == 0 )
      c = 10;
    XmTextFieldSetString(_o_rpm_1s_textfield, (char *) VkFormat("%d", c-1));
    oodidu.ood_rpm = (a*100) + (b*10) + c-1;
//cerr<<oodidu.ood_rpm<<endl;
    if ( !(net->write_idu((char *)&oodidu,SHIP_Ood_To_NPSNET_Type)) )
             cerr << "ERROR:\tCould not send OOD IDU." << endl;

} // End Deck::o_rpm_1s_minus()


void Deck::one_third_order ( Widget w, XtPointer callData )
{
    XmAnyCallbackStruct *cbs = (XmAnyCallbackStruct*) callData;

    //--- Comment out the following line when Deck::one_third_order is implemented:

    //::VkUnimplemented ( w, "Deck::one_third_order" );


    //--- Add application code for Deck::one_third_order here:
    oodidu.ood_port_bell = 1;
    if ( !(net->write_idu((char *)&oodidu,SHIP_Ood_To_NPSNET_Type)) )
             cerr << "ERROR:\tCould not send OOD IDU." << endl;

} // End Deck::one_third_order()


void play_voice_reply(const char *words){
   char command[255];

   strcpy(command,"/cm/npsnet/bin_demo/say "); 
//   strcpy(command,"./say "); 
   strcat(command,words);
   system((const char *)command);
}//play_voice_reply


void Deck::process_voice_cmd( Widget w, XtPointer callData )
{
    XmAnyCallbackStruct *cbs = (XmAnyCallbackStruct*) callData;

    //--- Comment out the following line when Deck::process_voice_cmd is implemented:

    //::VkUnimplemented ( w, "Deck::process_voice_cmd" );

    //--- Add application code for Deck::process_voice_cmd here:
    char	*str=XmTextFieldGetString(_voice_cmd_textfield);

    if(!strcmp(str,"")){
    }
    else //********************************************************
    if(!strcmp(str,"e")){
//cerr<<"hard_right_rudder"<<endl;
       play_voice_reply("hard right rudder aye sir");
       XmTextFieldSetString(_voice_cmd_textfield,"");
       EZ(_rudder_dial) = 45.0f;
       rudder_angle(w,callData);
    }
    else //********************************************************
    if(!strcmp(str,"f")){
//cerr<<"hard_left_rudder"<<endl;
       play_voice_reply("hard left rudder aye sir");
       XmTextFieldSetString(_voice_cmd_textfield,"");
       EZ(_rudder_dial) = 315.0f;
       rudder_angle(w,callData);
    }
    else //********************************************************
    if(!strcmp(str,"g")){
//cerr<<"shift_your_rudder"<<endl;
       play_voice_reply("shift my rudder aye sir");
       XmTextFieldSetString(_voice_cmd_textfield,"");
       EZ(_rudder_dial) = 360-EZ(_rudder_dial);
       rudder_angle(w,callData);
    }
    else //********************************************************
    if(!strcmp(str,"h")){
//cerr<<"rudder_amidships"<<endl;
       play_voice_reply("rudder amidships aye sir");
       XmTextFieldSetString(_voice_cmd_textfield,"");
       EZ(_rudder_dial) = 180.0f;
       rudder_angle(w,callData);
    }
    else //********************************************************
    if(!strcmp(str,"r")){
//cerr<<"right";
       play_voice_reply("okay");
    }
    else 
    if(!strcmp(str,"rd")){
//cerr<<"_full_rudder"<<endl;
       play_voice_reply("right full rudder aye sir");
       XmTextFieldSetString(_voice_cmd_textfield,"");
       EZ(_rudder_dial) = 67.5f;
       rudder_angle(w,callData);
    }
    else 
    if(!strcmp(str,"rc")){
//cerr<<"_std_rudder"<<endl;
       play_voice_reply("right standard rudder aye sir");
       XmTextFieldSetString(_voice_cmd_textfield,"");
       EZ(_rudder_dial) = 112.5f;
       rudder_angle(w,callData);
    }
    else 
    if(!strcmp(str,"rb")){
//cerr<<"_10_deg_rudder"<<endl;
       play_voice_reply("right 10 degrees rudder aye sir");
       XmTextFieldSetString(_voice_cmd_textfield,"");
       EZ(_rudder_dial) = 135.0f;
       rudder_angle(w,callData);
    }
    else 
    if(!strcmp(str,"ra")){
//cerr<<"_5_deg_rudder"<<endl;
       play_voice_reply("right 5 degrees rudder aye sir");
       XmTextFieldSetString(_voice_cmd_textfield,"");
       EZ(_rudder_dial) = 157.5f;
       rudder_angle(w,callData);
    }
    else //********************************************************
    if(!strcmp(str,"l")){
//cerr<<"left";
       play_voice_reply("okay");
    }
    else 
    if(!strcmp(str,"ld")){
//cerr<<"_full_rudder"<<endl;
       play_voice_reply("left full rudder aye sir");
       XmTextFieldSetString(_voice_cmd_textfield,"");
       EZ(_rudder_dial) = 292.5f;
       rudder_angle(w,callData);
    }
    else
    if(!strcmp(str,"lc")){
//cerr<<"_std_rudder"<<endl;
       play_voice_reply("left standard rudder aye sir");
       XmTextFieldSetString(_voice_cmd_textfield,"");
       EZ(_rudder_dial) = 247.5f;
       rudder_angle(w,callData);
    }
    else 
    if(!strcmp(str,"lb")){
//cerr<<"_10_deg_rudder"<<endl;
       play_voice_reply("left 10 degrees rudder aye sir");
       XmTextFieldSetString(_voice_cmd_textfield,"");
       EZ(_rudder_dial) = 225.0f;
       rudder_angle(w,callData);
    }
    else 
    if(!strcmp(str,"la")){
//cerr<<"_5_deg_rudder"<<endl;
       play_voice_reply("left 5 degrees rudder aye sir");
       XmTextFieldSetString(_voice_cmd_textfield,"");
       EZ(_rudder_dial) = 202.5f;
       rudder_angle(w,callData);
    }
    else //********************************************************
    if(!strcmp(str,"p")){
//cerr<<"port";
       play_voice_reply("okay");
    }
    else 
    if(!strcmp(str,"pu")){
//cerr<<"_stop"<<endl;
       play_voice_reply("port stop aye sir");
       XmTextFieldSetString(_voice_cmd_textfield,"");
       XmToggleButtonSetState(_o_stop_toggle,TRUE,TRUE);
       stop_order(w,callData);
    }
    else
    if(!strcmp(str,"pm")){
//cerr<<"_ahead_1/3"<<endl;
       play_voice_reply("port ahead one third aye sir");
       XmTextFieldSetString(_voice_cmd_textfield,"");
       XmToggleButtonSetState(_o_one_third_toggle,TRUE,TRUE);
       one_third_order(w,callData);
    }
    else 
    if(!strcmp(str,"pn")){
//cerr<<"_back_1/3"<<endl;
       play_voice_reply("port back one third aye sir");
       XmTextFieldSetString(_voice_cmd_textfield,"");
       XmToggleButtonSetState(_o_back_one_third_toggle,TRUE,TRUE);
       back_one_third_order(w,callData);
    }
    else 
    if(!strcmp(str,"pw")){
//cerr<<"_ahead_2/3"<<endl;
       play_voice_reply("port ahead two thirds aye sir");
       XmTextFieldSetString(_voice_cmd_textfield,"");
       XmToggleButtonSetState(_o_two_third_toggle,TRUE,TRUE);
       two_third_order(w,callData);
    }
    else 
    if(!strcmp(str,"px")){
//cerr<<"_back_2/3"<<endl;
       play_voice_reply("port back two thirds aye sir");
       XmTextFieldSetString(_voice_cmd_textfield,"");
       XmToggleButtonSetState(_o_back_two_third_toggle,TRUE,TRUE);
       back_two_third_order(w,callData);
    }
    else 
    if(!strcmp(str,"pj")){
//cerr<<"_ahead_std"<<endl;
       play_voice_reply("port ahead standard aye sir");
       XmTextFieldSetString(_voice_cmd_textfield,"");
       XmToggleButtonSetState(_o_stnd_toggle,TRUE,TRUE);
       stnd_order(w,callData);
    }
    else 
    if(!strcmp(str,"py")){
//cerr<<"_ahead_full"<<endl;
       play_voice_reply("port ahead full aye sir");
       XmTextFieldSetString(_voice_cmd_textfield,"");
       XmToggleButtonSetState(_o_full_toggle,TRUE,TRUE);
       full_order(w,callData);
    }
    else 
    if(!strcmp(str,"pz")){
//cerr<<"_back_full"<<endl;
       play_voice_reply("port back full aye sir");
       XmTextFieldSetString(_voice_cmd_textfield,"");
       XmToggleButtonSetState(_o_backfull_toggle,TRUE,TRUE);
       back_full_order(w,callData);
    }
    else 
    if(!strcmp(str,"pv")){
//cerr<<"_ahead_flank"<<endl;
       play_voice_reply("port ahead flank aye sir");
       XmTextFieldSetString(_voice_cmd_textfield,"");
       XmToggleButtonSetState(_o_flank_toggle,TRUE,TRUE);
       flank_order(w,callData);
    }
    else //********************************************************
    if(!strcmp(str,"s")){
//cerr<<"stbd";
       play_voice_reply("okay");
    }
    else 
    if(!strcmp(str,"su")){
//cerr<<"_stop"<<endl;
       play_voice_reply("starboard stop aye sir");
       XmTextFieldSetString(_voice_cmd_textfield,"");
       XmToggleButtonSetState(_o_stop_toggle1,TRUE,TRUE);
       s_stop_order(w,callData);
    }
    else
    if(!strcmp(str,"sm")){
//cerr<<"_ahead_1/3"<<endl;
       play_voice_reply("starboard ahead one third aye sir");
       XmTextFieldSetString(_voice_cmd_textfield,"");
       XmToggleButtonSetState(_o_one_third_toggle1,TRUE,TRUE);
       s_one_third_order(w,callData);
    }
    else 
    if(!strcmp(str,"sn")){
//cerr<<"_back_1/3"<<endl;
       play_voice_reply("starboard back one third aye sir");
       XmTextFieldSetString(_voice_cmd_textfield,"");
       XmToggleButtonSetState(_o_back_one_third_toggle1,TRUE,TRUE);
       s_back_one_third_order(w,callData);
    }
    else 
    if(!strcmp(str,"sw")){
//cerr<<"_ahead_2/3"<<endl;
       play_voice_reply("starboard ahead two thirds aye sir");
       XmTextFieldSetString(_voice_cmd_textfield,"");
       XmToggleButtonSetState(_o_two_third_toggle1,TRUE,TRUE);
       s_two_third_order(w,callData);
    }
    else 
    if(!strcmp(str,"sx")){
//cerr<<"_back_2/3"<<endl;
       play_voice_reply("starboard back two thirds aye sir");
       XmTextFieldSetString(_voice_cmd_textfield,"");
       XmToggleButtonSetState(_o_back_two_third_toggle1,TRUE,TRUE);
       s_back_two_third_order(w,callData);
    }
    else 
    if(!strcmp(str,"sj")){
//cerr<<"_ahead_std"<<endl;
       play_voice_reply("starboard ahead standard aye sir");
       XmTextFieldSetString(_voice_cmd_textfield,"");
       XmToggleButtonSetState(_o_stnd_toggle1,TRUE,TRUE);
       s_stnd_order(w,callData);
    }
    else 
    if(!strcmp(str,"sy")){
//cerr<<"_ahead_full"<<endl;
       play_voice_reply("starboard ahead full aye sir");
       XmTextFieldSetString(_voice_cmd_textfield,"");
       XmToggleButtonSetState(_o_full_toggle1,TRUE,TRUE);
       s_full_order(w,callData);
    }
    else 
    if(!strcmp(str,"sz")){
//cerr<<"_back_full"<<endl;
       play_voice_reply("starboard back full aye sir");
       XmTextFieldSetString(_voice_cmd_textfield,"");
       XmToggleButtonSetState(_o_backfull_toggle1,TRUE,TRUE);
       s_back_full_order(w,callData);
    }
    else 
    if(!strcmp(str,"sv")){
//cerr<<"_ahead_flank"<<endl;
       play_voice_reply("starboard ahead flank aye sir");
       XmTextFieldSetString(_voice_cmd_textfield,"");
       XmToggleButtonSetState(_o_flank_toggle1,TRUE,TRUE);
       s_flank_order(w,callData);
    }
    else //********************************************************
    if(!strcmp(str,"o")){
//cerr<<"all";
       play_voice_reply("okay");
    }
    else 
    if(!strcmp(str,"ou")){
//cerr<<"_stop"<<endl;
       play_voice_reply("all stop aye sir");
       XmTextFieldSetString(_voice_cmd_textfield,"");
       XmToggleButtonSetState(_o_stop_toggle,TRUE,TRUE);
       stop_order(w,callData);
       XmToggleButtonSetState(_o_stop_toggle1,TRUE,TRUE);
       s_stop_order(w,callData);
    }
    else
    if(!strcmp(str,"om")){
//cerr<<"_ahead_1/3"<<endl;
       play_voice_reply("all ahead one third aye sir");
       XmTextFieldSetString(_voice_cmd_textfield,"");
       XmToggleButtonSetState(_o_one_third_toggle,TRUE,TRUE);
       one_third_order(w,callData);
       XmToggleButtonSetState(_o_one_third_toggle1,TRUE,TRUE);
       s_one_third_order(w,callData);
    }
    else 
    if(!strcmp(str,"on")){
//cerr<<"_back_1/3"<<endl;
       play_voice_reply("all back one third aye sir");
       XmTextFieldSetString(_voice_cmd_textfield,"");
       XmToggleButtonSetState(_o_back_one_third_toggle,TRUE,TRUE);
       back_one_third_order(w,callData);
       XmToggleButtonSetState(_o_back_one_third_toggle1,TRUE,TRUE);
       s_back_one_third_order(w,callData);
    }
    else 
    if(!strcmp(str,"ow")){
//cerr<<"_ahead_2/3"<<endl;
       play_voice_reply("all ahead two thirds aye sir");
       XmTextFieldSetString(_voice_cmd_textfield,"");
       XmToggleButtonSetState(_o_two_third_toggle,TRUE,TRUE);
       two_third_order(w,callData);
       XmToggleButtonSetState(_o_two_third_toggle1,TRUE,TRUE);
       s_two_third_order(w,callData);
    }
    else 
    if(!strcmp(str,"ox")){
//cerr<<"_back_2/3"<<endl;
       play_voice_reply("all back two thirds aye sir");
       XmTextFieldSetString(_voice_cmd_textfield,"");
       XmToggleButtonSetState(_o_back_two_third_toggle,TRUE,TRUE);
       back_two_third_order(w,callData);
       XmToggleButtonSetState(_o_back_two_third_toggle1,TRUE,TRUE);
       s_back_two_third_order(w,callData);
    }
    else 
    if(!strcmp(str,"oj")){
//cerr<<"_ahead_std"<<endl;
       play_voice_reply("all ahead standard aye sir");
       XmTextFieldSetString(_voice_cmd_textfield,"");
       XmToggleButtonSetState(_o_stnd_toggle,TRUE,TRUE);
       stnd_order(w,callData);
       XmToggleButtonSetState(_o_stnd_toggle1,TRUE,TRUE);
       s_stnd_order(w,callData);
    }
    else 
    if(!strcmp(str,"oy")){
//cerr<<"_ahead_full"<<endl;
       play_voice_reply("all ahead full aye sir");
       XmTextFieldSetString(_voice_cmd_textfield,"");
       XmToggleButtonSetState(_o_full_toggle,TRUE,TRUE);
       full_order(w,callData);
       XmToggleButtonSetState(_o_full_toggle1,TRUE,TRUE);
       s_full_order(w,callData);
    }
    else 
    if(!strcmp(str,"oz")){
//cerr<<"_back_full"<<endl;
       play_voice_reply("all back full aye sir");
       XmTextFieldSetString(_voice_cmd_textfield,"");
       XmToggleButtonSetState(_o_backfull_toggle,TRUE,TRUE);
       back_full_order(w,callData);
       XmToggleButtonSetState(_o_backfull_toggle1,TRUE,TRUE);
       s_back_full_order(w,callData);
    }
    else 
    if(!strcmp(str,"ov")){
//cerr<<"_ahead_flank"<<endl;
       play_voice_reply("all ahead flank aye sir");
       XmTextFieldSetString(_voice_cmd_textfield,"");
       XmToggleButtonSetState(_o_flank_toggle,TRUE,TRUE);
       flank_order(w,callData);
       XmToggleButtonSetState(_o_flank_toggle1,TRUE,TRUE);
       s_flank_order(w,callData);
    }
    else //********************************************************
    if((strcmp(str,"i")>=0) && (strcmp(str,"j")<0)){
       size_t len=strlen(str);
       if((len==4)&&isdigit(str[3])) {
          str++;
          char *ptr=str, ch[2]; ch[1]='\0'; 
          char say[25];
//cerr<<"indicate "<<str<<endl;
          strcpy(say, "indicate ");
          XmTextFieldSetString(_voice_cmd_textfield,"");
          strncpy(ch,ptr++,1); strcat(say,ch); strcat(say," ");
          XmTextFieldSetString(_o_rpm_100s_textfield,ch);
          strncpy(ch,ptr++,1); strcat(say,ch); strcat(say," ");
          XmTextFieldSetString(_o_rpm_10s_textfield,ch);
          strncpy(ch,ptr,1); strcat(say,ch); strcat(say," ");
          XmTextFieldSetString(_o_rpm_1s_textfield,ch);
          oodidu.ood_rpm = atoi(str);
          strcat(say,"aye sir");
          play_voice_reply(say);
//cerr<<oodidu.ood_rpm<<endl;
          if ( !(net->write_idu((char *)&oodidu,SHIP_Ood_To_NPSNET_Type)) )
              cerr << "ERROR:\tCould not send OOD IDU." << endl;    
       }
       else if((len > 4) || 
               ( (len > 1)&&(len < 5)&&!isdigit(str[len-1]) ) ) {
//cerr<<"invalid: "<<str<<endl;
              XmTextFieldSetString(_voice_cmd_textfield,"");
            }
    }
    else {//********************************************************
//cerr<<"***Unknown:"<<str<<endl;
       play_voice_reply("orders to the helm");
       XmTextFieldSetString(_voice_cmd_textfield,"");
    }
}


void Deck::rudder_angle ( Widget w, XtPointer callData )
{
    char 	*direction;
    XmAnyCallbackStruct *cbs = (XmAnyCallbackStruct*) callData;

    //--- Comment out the following line when Deck::rudder_angle is implemented:

    //::VkUnimplemented ( w, "Deck::rudder_angle" );


    //--- Add application code for Deck::rudder_angle here:
    oodidu.ood_rudder_angle = (180.0f - (float)EZ(_rudder_dial)) / 4.5f;
//cerr<<"                                             \r";
//cerr<<"dial:"<<(float)EZ(_rudder_dial)<<"\r";
    if (oodidu.ood_rudder_angle > 30.0f) oodidu.ood_rudder_angle = 30.0f;
    if (oodidu.ood_rudder_angle < -30.0f) oodidu.ood_rudder_angle = -30.0f;
    if (oodidu.ood_rudder_angle > 0.0f) direction = "R";
    else if (oodidu.ood_rudder_angle < 0.0f) direction = "L";
         else direction = " ";
    XmTextFieldSetString(_actual_rudder_textfield,
      (char *) VkFormat("%s %3.2f", direction, fabs(oodidu.ood_rudder_angle)));
    if ( !(net->write_idu((char *)&oodidu,SHIP_Ood_To_NPSNET_Type)) )
             cerr << "ERROR:\tCould not send OOD IDU." << endl;

} // End Deck::rudder_angle()


void Deck::s_back_full_order ( Widget w, XtPointer callData )
{
    XmAnyCallbackStruct *cbs = (XmAnyCallbackStruct*) callData;

    //--- Comment out the following line when Deck::s_back_full_order is implemented:

    //::VkUnimplemented ( w, "Deck::s_back_full_order" );


    //--- Add application code for Deck::s_back_full_order here:
    oodidu.ood_stbd_bell = -3;
    if ( !(net->write_idu((char *)&oodidu,SHIP_Ood_To_NPSNET_Type)) )
             cerr << "ERROR:\tCould not send OOD IDU." << endl;

} // End Deck::s_back_full_order()


void Deck::s_back_one_third_order ( Widget w, XtPointer callData )
{
    XmAnyCallbackStruct *cbs = (XmAnyCallbackStruct*) callData;

    //--- Comment out the following line when Deck::s_back_one_third_order is implemented:

    //::VkUnimplemented ( w, "Deck::s_back_one_third_order" );


    //--- Add application code for Deck::s_back_one_third_order here:
    oodidu.ood_stbd_bell = -1;
    if ( !(net->write_idu((char *)&oodidu,SHIP_Ood_To_NPSNET_Type)) )
             cerr << "ERROR:\tCould not send OOD IDU." << endl;

} // End Deck::s_back_one_third_order()


void Deck::s_back_two_third_order ( Widget w, XtPointer callData )
{
    XmAnyCallbackStruct *cbs = (XmAnyCallbackStruct*) callData;

    //--- Comment out the following line when Deck::s_back_two_third_order is implemented:

    //::VkUnimplemented ( w, "Deck::s_back_two_third_order" );


    //--- Add application code for Deck::s_back_two_third_order here:
    oodidu.ood_stbd_bell = -2;
    if ( !(net->write_idu((char *)&oodidu,SHIP_Ood_To_NPSNET_Type)) )
             cerr << "ERROR:\tCould not send OOD IDU." << endl;

} // End Deck::s_back_two_third_order()


void Deck::s_flank_order ( Widget w, XtPointer callData )
{
    XmAnyCallbackStruct *cbs = (XmAnyCallbackStruct*) callData;

    //--- Comment out the following line when Deck::s_flank_order is implemented:

    //::VkUnimplemented ( w, "Deck::s_flank_order" );


    //--- Add application code for Deck::s_flank_order here:
    oodidu.ood_stbd_bell = 5;
    if ( !(net->write_idu((char *)&oodidu,SHIP_Ood_To_NPSNET_Type)) )
             cerr << "ERROR:\tCould not send OOD IDU." << endl;

} // End Deck::s_flank_order()


void Deck::s_full_order ( Widget w, XtPointer callData )
{
    XmAnyCallbackStruct *cbs = (XmAnyCallbackStruct*) callData;

    //--- Comment out the following line when Deck::s_full_order is implemented:

    //::VkUnimplemented ( w, "Deck::s_full_order" );


    //--- Add application code for Deck::s_full_order here:
    oodidu.ood_stbd_bell = 4;
    if ( !(net->write_idu((char *)&oodidu,SHIP_Ood_To_NPSNET_Type)) )
             cerr << "ERROR:\tCould not send OOD IDU." << endl;

} // End Deck::s_full_order()


void Deck::s_one_third_order ( Widget w, XtPointer callData )
{
    XmAnyCallbackStruct *cbs = (XmAnyCallbackStruct*) callData;

    //--- Comment out the following line when Deck::s_one_third_order is implemented:

    //::VkUnimplemented ( w, "Deck::s_one_third_order" );


    //--- Add application code for Deck::s_one_third_order here:
    oodidu.ood_stbd_bell = 1;
    if ( !(net->write_idu((char *)&oodidu,SHIP_Ood_To_NPSNET_Type)) )
             cerr << "ERROR:\tCould not send OOD IDU." << endl;

} // End Deck::s_one_third_order()


void Deck::s_stnd_order ( Widget w, XtPointer callData )
{
    XmAnyCallbackStruct *cbs = (XmAnyCallbackStruct*) callData;

    //--- Comment out the following line when Deck::s_stnd_order is implemented:

    //::VkUnimplemented ( w, "Deck::s_stnd_order" );


    //--- Add application code for Deck::s_stnd_order here:
    oodidu.ood_stbd_bell = 3;
    if ( !(net->write_idu((char *)&oodidu,SHIP_Ood_To_NPSNET_Type)) )
             cerr << "ERROR:\tCould not send OOD IDU." << endl;

} // End Deck::s_stnd_order()


void Deck::s_stop_order ( Widget w, XtPointer callData )
{
    XmAnyCallbackStruct *cbs = (XmAnyCallbackStruct*) callData;

    //--- Comment out the following line when Deck::s_stop_order is implemented:

    //::VkUnimplemented ( w, "Deck::s_stop_order" );


    //--- Add application code for Deck::s_stop_order here:
    oodidu.ood_stbd_bell = 0;
    if ( !(net->write_idu((char *)&oodidu,SHIP_Ood_To_NPSNET_Type)) )
             cerr << "ERROR:\tCould not send OOD IDU." << endl;

} // End Deck::s_stop_order()


void Deck::s_two_third_order ( Widget w, XtPointer callData )
{
    XmAnyCallbackStruct *cbs = (XmAnyCallbackStruct*) callData;

    //--- Comment out the following line when Deck::s_two_third_order is implemented:

    //::VkUnimplemented ( w, "Deck::s_two_third_order" );


    //--- Add application code for Deck::s_two_third_order here:
    oodidu.ood_stbd_bell = 2;
    if ( !(net->write_idu((char *)&oodidu,SHIP_Ood_To_NPSNET_Type)) )
             cerr << "ERROR:\tCould not send OOD IDU." << endl;

} // End Deck::s_two_third_order()


void Deck::stnd_order ( Widget w, XtPointer callData )
{
    XmAnyCallbackStruct *cbs = (XmAnyCallbackStruct*) callData;

    //--- Comment out the following line when Deck::stnd_order is implemented:

    //::VkUnimplemented ( w, "Deck::stnd_order" );


    //--- Add application code for Deck::stnd_order here:
    oodidu.ood_port_bell = 3;
    if ( !(net->write_idu((char *)&oodidu,SHIP_Ood_To_NPSNET_Type)) )
             cerr << "ERROR:\tCould not send OOD IDU." << endl;

} // End Deck::stnd_order()


void Deck::stop_order ( Widget w, XtPointer callData )
{
    XmAnyCallbackStruct *cbs = (XmAnyCallbackStruct*) callData;

    //--- Comment out the following line when Deck::stop_order is implemented:

    //::VkUnimplemented ( w, "Deck::stop_order" );


    //--- Add application code for Deck::stop_order here:
    oodidu.ood_port_bell = 0;
    if ( !(net->write_idu((char *)&oodidu,SHIP_Ood_To_NPSNET_Type)) )
             cerr << "ERROR:\tCould not send OOD IDU." << endl;

} // End Deck::stop_order()


void Deck::two_third_order ( Widget w, XtPointer callData )
{
    XmAnyCallbackStruct *cbs = (XmAnyCallbackStruct*) callData;

    //--- Comment out the following line when Deck::two_third_order is implemented:

    //::VkUnimplemented ( w, "Deck::two_third_order" );


    //--- Add application code for Deck::two_third_order here:
    oodidu.ood_port_bell = 2;
    if ( !(net->write_idu((char *)&oodidu,SHIP_Ood_To_NPSNET_Type)) )
             cerr << "ERROR:\tCould not send OOD IDU." << endl;

} // End Deck::two_third_order()


void Deck::setParent( VkSimpleWindow  * parent )
{
    // Store a pointer to the parent VkWindow. This can
    // be useful for accessing the menubar from this class.


    _parent = parent;


} // End Deck::setParent()




//---- End generated code section

