
//////////////////////////////////////////////////////////////////////
// This is a driver ViewKit program generated by RapidApp 

//
// This program instantiates a ViewKit VkApp object and creates
// any main window objects that are meant to be shown at startup.
// There should rarely be a reason to modify this file.
// Make application-specific changes in the classes created
// by the main window classes
// Some applications may wish to change this code to instantiate
// a different application class, however.
//////////////////////////////////////////////////////////////////////

//NEW to make this application run correctly you must run 
//           xrdb -merge Application
// This should be placed into a script to run the program

// Headers for classes used in this program
#include <Vk/VkApp.h>
#include <iostream.h>
#include <Xm/TextF.h> 
#include <idunetlib.h>
#include <idu.h>      

#include "ShipControlWindowMainWindow.h"

//SHIP_MSG_DATA       *packet;
OodToNPSNETIDU       oodidu;
IDU_net_manager     *net;

void main ( int argc, char **argv )
{
    extern void InitEZ(void);

    InitEZ();

    VkApp       *app;

 //COMMS----------------------------------------------   
    int op = 0 ;
    extern char *optarg;
    extern int optind, operr;

    // Multicast Defaults
    int multicast = TRUE;
    u_short port;
    char group[25];
    u_char ttl = IDU_DEF_MC_TTL;
    port = 0;
    int loopback = FALSE;
    //int loopback = TRUE;

    char net_interface[20];
    
    //initialize global data structures
    oodidu.ood_rudder_angle = 0;   
    oodidu.ood_rpm = 0;   
    oodidu.ood_port_bell = 0;   
    oodidu.ood_stbd_bell = 0;   
    oodidu.space_holder = 0;

 //COMMS----------------------------------------------   

    strncpy ( group, IDU_DEF_MC_GROUP,25 );   //COMMS
    strcpy ( net_interface, "" );             //COMMS

 //COMMS----------------------------------------------   
   while ((op = getopt(argc, argv, "P:p:G:g:T:t:BblLI:i:")) != -1)
      {
      switch (op)
         {
         case 'p':
         case 'P':
            port = u_short(atoi(optarg));
            break;
         case 'G':
         case 'g':
            strncpy ( group, optarg, 25 );
            break;
         case 't':
         case 'T':
            ttl =  u_char(atoi(optarg));
            break;
         case 'b':
         case 'B':
            multicast = FALSE;
            break; 
         case 'l':
         case 'L':
            loopback = TRUE;
            break;
         case 'i':
         case 'I':
            strncpy ( net_interface, optarg, 19 );
            break;
         default:
            cerr << "Usage:  idudump [-p <network port>] \n"
                 << "                [-i <network interface>] \n"
                 << "                [-g <multicast group>] \n"
                 << "                [-t <multicast ttl>] \n"
                 << "                [-b   (to enable broadcast) \n";
            exit(0);
            break;
         }
      }

   if ( multicast )
      {
      if ( port == 0 )
         port = IDU_DEF_MC_PORT;
      net = new IDU_net_manager ( group, port, ttl, net_interface,
                                  loopback );
      }
   else
      {
      if ( port == 0 )
         port = IDU_DEF_BC_PORT;
      net = new IDU_net_manager ( port, net_interface, loopback );
      }

   if ( !net->net_open() )
      {
      cerr << "Could not open network." << endl;
      exit(0);
      }
   else
      {
      net->add_to_receive_list(Test_Type);
      net->add_to_receive_list(NPSNET_To_SHIP_Type);
      }

   if ( multicast )
      {
      cerr << "\tMode:     \tMulticast" << endl;
      cerr << "\tPort:     \t" << (int)port << endl;
      cerr << "\tGroup:    \t" << group << endl;
      cerr << "\tTTL:      \t" << (int)ttl << endl;
      cerr << "\tInterface:\t" << net_interface << endl;
      cerr << "\tLoopback: \t";
      if ( loopback )
         cerr << "ON" << endl;
      else
         cerr << "OFF" << endl;
      cerr << endl;
      }
   else
      {
      cerr << "\tMode:     \tBroadcast" << endl;
      cerr << "\tPort:     \t" << (int)port << endl;
      cerr << "\tInterface:\t" << net_interface << endl << endl;
      cerr << "\tLoopback: \t";
      if ( loopback )
         cerr << "ON" << endl;
      else
         cerr << "OFF" << endl;
      cerr << endl;
      }
  //COMMS----------------------------------------------   


    //initialize packet
    //packet = new SHIP_MSG_DATA;
    
    // Create an application object
    app = new VkApp("Application", &argc, argv); 

    // Create the top level windows

    VkSimpleWindow *shipControlWindow  = 
                    new ShipControlWindowMainWindow("shipControlWindow");
    shipControlWindow->show();
cerr<<"Starting Application..."<<endl;
    app->run ();
}
