
//////////////////////////////////////////////////////////////
//
// Header file for DeckTabbedDeck
//
//    This file is generated by RapidApp
//
//    This class is derived from VkTabbedDeck which 
//    implements the user interface created in 
//    the interface builder. This class contains virtual
//    functions that are called from the user interface.
//
//    When you modify this header file, limit your changes to adding
//    members below the "//--- End generated code section" markers
//
//    This will allow the builder to integrate changes more easily
//
//    This class is a ViewKit user interface "component".
//    For more information on how components are used, see the
//    "ViewKit Programmers' Manual", and the RapidApp
//    User's Guide.
//////////////////////////////////////////////////////////////
#ifndef DECKTABBEDDECK_H
#define DECKTABBEDDECK_H
#include "VkTabbedDeck.h"
#include <Vk/VkSimpleWindow.h>
//---- End generated headers


//---- DeckTabbedDeck class declaration

class DeckTabbedDeck : public VkTabbedDeck
{

  public:

    DeckTabbedDeck(const char *, Widget);
    DeckTabbedDeck(const char *);
    ~DeckTabbedDeck();
    const char *  className();
    virtual void setParent(VkSimpleWindow  *);

    void update();
    //---- End generated code section


    protected:


    // Classes created by this class

    class Helm *_helm;
    class Ood *_ood;
    class Weaps *_weaps;

    // Widgets created by this class

    Widget  _deck;




    //--- End generated code section



    VkSimpleWindow * _parent;

  private:

};
#endif

