
//////////////////////////////////////////////////////////////
//
// Header file for HelmUI
//
//    This file is generated by RapidApp
//
//    This class implements the user interface potion of a class
//    the interface builder. Normally it is not used directly.
//    Instead the subclass, Helm is instantiated
//
//    To extend or alter the behavior of this class, you should
//    modify the Helm files
//
//    If you do modify this class, limit your changes to adding
//    members below the "//--- End generated code section" markers
//
//    This will allow the builder to integrate changes more easily
//
//    This class is a ViewKit user interface "component".
//    For more information on how components are used, see the
//    "ViewKit Programmers' Manual", and the RapidApp
//    User's Guide.
//
//////////////////////////////////////////////////////////////
#ifndef HELMUI_H
#define HELMUI_H
#include <Vk/VkComponent.h>


//---- End generated headers

class HelmUI : public VkComponent
{ 

  public:

    HelmUI(const char *, Widget);
    HelmUI(const char *);
    ~HelmUI();
    void create ( Widget );
    const char *  className();

    //--- End generated code section

  protected:


    // Widgets created by this class

    Widget  _actual_h_course_label;
    Widget  _actual_h_course_textfield;
    Widget  _actual_h_depth_label;
    Widget  _actual_h_depth_textfield;
    Widget  _actual_h_speed_label;
    Widget  _actual_h_speed_textfield;
    Widget  _actual_helm_form;
    Widget  _actual_helm_frame;
    Widget  _actual_helm_label;
    Widget  _actual_helm_separator;
    Widget  _back_full_toggle;
    Widget  _back_half_toggle;
    Widget  _back_stnd_toggle;
    Widget  _compas_depth_form;
    Widget  _compass_depth_frame;
    Widget  _compass_dial;
    Widget  _compass_label;
    Widget  _compass_textfield;
    Widget  _depth_dial;
    Widget  _depth_label;
    Widget  _depth_textfield;
    Widget  _fairwater_textfield;
    Widget  _flank_toggle;
    Widget  _full_toggle;
    Widget  _fwtr_label;
    Widget  _fwtr_planes_dial;
    Widget  _half_toggle;
    Widget  _helm;
    Widget  _order_h_course_label;
    Widget  _order_h_course_textfield;
    Widget  _order_h_depth_label;
    Widget  _order_h_depth_textfield;
    Widget  _order_h_speed_label;
    Widget  _order_h_speed_textfield;
    Widget  _order_helm_label;
    Widget  _order_helm_separator;
    Widget  _ordered_helm_form;
    Widget  _ordered_helm_frame;
    Widget  _planes_form;
    Widget  _planes_frame;
    Widget  _radiobox;
    Widget  _rowcolumn;
    Widget  _rudder_dial;
    Widget  _rudder_label;
    Widget  _rudder_textfield;
    Widget  _stern_label;
    Widget  _stern_plns_dial;
    Widget  _stern_textfield;
    Widget  _stnd_toggle1;
    Widget  _stop_toggle;
    Widget  _telegraph_frame;




    // These virtual functions are called from the private callbacks (above)
    // Intended to be overriden in derived classes to define actions

    virtual void back_full_actual ( Widget, XtPointer );
    virtual void back_half_actual ( Widget, XtPointer );
    virtual void back_stnd_actual ( Widget, XtPointer );
    virtual void flank_actual ( Widget, XtPointer );
    virtual void full_actual ( Widget, XtPointer );
    virtual void half_actual ( Widget, XtPointer );
    virtual void stnd_actual ( Widget, XtPointer );
    virtual void stop_actual ( Widget, XtPointer );

    //--- End generated code section

  private: 
    // Array of default resources

    static String      _defaultHelmUIResources[];

    // Callbacks to interface with Motif

    static void back_full_actualCallback ( Widget, XtPointer, XtPointer );
    static void back_half_actualCallback ( Widget, XtPointer, XtPointer );
    static void back_stnd_actualCallback ( Widget, XtPointer, XtPointer );
    static void flank_actualCallback ( Widget, XtPointer, XtPointer );
    static void full_actualCallback ( Widget, XtPointer, XtPointer );
    static void half_actualCallback ( Widget, XtPointer, XtPointer );
    static void stnd_actualCallback ( Widget, XtPointer, XtPointer );
    static void stop_actualCallback ( Widget, XtPointer, XtPointer );

    //--- End generated code section

};
#endif

