
//////////////////////////////////////////////////////////////
//
// Header file for Helm
//
//    This file is generated by RapidApp
//
//    This class is derived from HelmUI which 
//    implements the user interface created in 
//    the interface builder. This class contains virtual
//    functions that are called from the user interface.
//
//    When you modify this header file, limit your changes to adding
//    members below the "//--- End generated code section" markers
//
//    This will allow the builder to integrate changes more easily
//
//    This class is a ViewKit user interface "component".
//    For more information on how components are used, see the
//    "ViewKit Programmers' Manual", and the RapidApp
//    User's Guide.
//////////////////////////////////////////////////////////////
#ifndef HELM_H
#define HELM_H
#include "HelmUI.h"

//---- End generated headers


//---- Helm class declaration

class Helm : public HelmUI
{

  public:

    Helm(const char *, Widget);
    Helm(const char *);
    ~Helm();
    const char *  className();
 
    void update();
    //---- End generated code section


  protected:


    // These functions will be called as a result of callbacks
    // registered in HelmUI

    virtual void back_full_actual ( Widget, XtPointer );
    virtual void back_half_actual ( Widget, XtPointer );
    virtual void back_stnd_actual ( Widget, XtPointer );
    virtual void flank_actual ( Widget, XtPointer );
    virtual void full_actual ( Widget, XtPointer );
    virtual void half_actual ( Widget, XtPointer );
    virtual void stnd_actual ( Widget, XtPointer );
    virtual void stop_actual ( Widget, XtPointer );

    //---- End generated code section


  private:

};
#endif

