
//////////////////////////////////////////////////////////////
//
// Header file for Ood
//
//    This file is generated by RapidApp
//
//    This class is derived from OodUI which 
//    implements the user interface created in 
//    the interface builder. This class contains virtual
//    functions that are called from the user interface.
//
//    When you modify this header file, limit your changes to adding
//    members below the "//--- End generated code section" markers
//
//    This will allow the builder to integrate changes more easily
//
//    This class is a ViewKit user interface "component".
//    For more information on how components are used, see the
//    "ViewKit Programmers' Manual", and the RapidApp
//    User's Guide.
//////////////////////////////////////////////////////////////
#ifndef OOD_H
#define OOD_H
#include "OodUI.h"

//---- End generated headers


//---- Ood class declaration

class Ood : public OodUI
{

  public:

    Ood(const char *, Widget);
    Ood(const char *);
    ~Ood();
    const char *  className();
   
    void update();
    //---- End generated code section


  protected:


    // These functions will be called as a result of callbacks
    // registered in OodUI

    virtual void back_full_order ( Widget, XtPointer );
    virtual void back_half_order ( Widget, XtPointer );
    virtual void back_stnd_order ( Widget, XtPointer );
    virtual void embt_blow_off ( Widget, XtPointer );
    virtual void embt_blow_on ( Widget, XtPointer );
    virtual void flank_order ( Widget, XtPointer );
    virtual void full_order ( Widget, XtPointer );
    virtual void half_order ( Widget, XtPointer );
    virtual void mbt_vents_open ( Widget, XtPointer );
    virtual void mbt_vents_shut ( Widget, XtPointer );
    virtual void o_crs_100s_add ( Widget, XtPointer );
    virtual void o_crse_100s_minus ( Widget, XtPointer );
    virtual void o_crse_10s_add ( Widget, XtPointer );
    virtual void o_crse_10s_minus ( Widget, XtPointer );
    virtual void o_crse_1s_add ( Widget, XtPointer );
    virtual void o_crse_1s_minus ( Widget, XtPointer );
    virtual void o_dpth_1000s_add ( Widget, XtPointer );
    virtual void o_dpth_1000s_minus ( Widget, XtPointer );
    virtual void o_dpth_100s_add ( Widget, XtPointer );
    virtual void o_dpth_100s_minus ( Widget, XtPointer );
    virtual void o_dpth_10s_add ( Widget, XtPointer );
    virtual void o_dpth_10s_minus ( Widget, XtPointer );
    virtual void o_dpth_1s_add ( Widget, XtPointer );
    virtual void o_dpth_1s_minus ( Widget, XtPointer );
    virtual void scope_lower ( Widget, XtPointer );
    virtual void scope_mark ( Widget, XtPointer );
    virtual void scope_raise ( Widget, XtPointer );
    virtual void scope_view_down ( Widget, XtPointer );
    virtual void scope_view_left ( Widget, XtPointer );
    virtual void scope_view_right ( Widget, XtPointer );
    virtual void scope_view_up ( Widget, XtPointer );
    virtual void stnd_order ( Widget, XtPointer );
    virtual void stop_order ( Widget, XtPointer );

    //---- End generated code section


  private:

};
#endif

