
//////////////////////////////////////////////////////////////
//
// Header file for OodUI
//
//    This file is generated by RapidApp
//
//    This class implements the user interface potion of a class
//    the interface builder. Normally it is not used directly.
//    Instead the subclass, Ood is instantiated
//
//    To extend or alter the behavior of this class, you should
//    modify the Ood files
//
//    If you do modify this class, limit your changes to adding
//    members below the "//--- End generated code section" markers
//
//    This will allow the builder to integrate changes more easily
//
//    This class is a ViewKit user interface "component".
//    For more information on how components are used, see the
//    "ViewKit Programmers' Manual", and the RapidApp
//    User's Guide.
//
//////////////////////////////////////////////////////////////
#ifndef OODUI_H
#define OODUI_H
#include <Vk/VkComponent.h>


//---- End generated headers

class OodUI : public VkComponent
{ 

  public:

    OodUI(const char *, Widget);
    OodUI(const char *);
    ~OodUI();
    void create ( Widget );
    const char *  className();

    //--- End generated code section

  protected:


    // Widgets created by this class

    Widget  _actual_OOD_form;
    Widget  _actual_OOD_frame;
    Widget  _actual_OOD_label;
    Widget  _actual_OOD_separator;
    Widget  _actual_O_course_label;
    Widget  _actual_O_course_textfield;
    Widget  _actual_O_depth_label;
    Widget  _actual_O_depth_textfield;
    Widget  _actual_O_speed_label;
    Widget  _actual_O_speed_textfield;
    Widget  _bearing_label;
    Widget  _course_ood_form;
    Widget  _course_ood_frame;
    Widget  _course_ood_label;
    Widget  _depth_ood_form;
    Widget  _depth_ood_frame;
    Widget  _depth_ood_label;
    Widget  _embt_label;
    Widget  _embt_off_toggle;
    Widget  _embt_on_toggle;
    Widget  _mbt_form;
    Widget  _mbt_frame;
    Widget  _mbt_label;
    Widget  _mbts_open_toggle;
    Widget  _mbts_shut_toggle;
    Widget  _o_backfull_toggle;
    Widget  _o_backhalf_toggle;
    Widget  _o_backstnd_toggle;
    Widget  _o_course_100s_textfield;
    Widget  _o_course_10s_textfield;
    Widget  _o_course_1s_textfield;
    Widget  _o_crs_100s_up_arrow;
    Widget  _o_crse_100s_dwn_arrow;
    Widget  _o_crse_10s_dwn_arrow;
    Widget  _o_crse_10s_up_arrow;
    Widget  _o_crse_1s_dwn_arrow;
    Widget  _o_crse_1s_up_arrow;
    Widget  _o_dpth_1000s_dwn_arrow;
    Widget  _o_dpth_1000s_textfield;
    Widget  _o_dpth_1000s_up_arrow;
    Widget  _o_dpth_100s_dwn_arrow;
    Widget  _o_dpth_100s_textfield;
    Widget  _o_dpth_100s_up_arrow;
    Widget  _o_dpth_10s_dwn_arrow;
    Widget  _o_dpth_10s_textfield;
    Widget  _o_dpth_10s_up_arrow;
    Widget  _o_dpth_1s_dwn_arrow;
    Widget  _o_dpth_1s_textfield;
    Widget  _o_dpth_1s_up_arrow;
    Widget  _o_flank_toggle;
    Widget  _o_full_toggle;
    Widget  _o_half_toggle;
    Widget  _o_stnd_toggle;
    Widget  _o_stop_toggle;
    Widget  _ood;
    Widget  _ood_order_label;
    Widget  _periscope_label;
    Widget  _radiobox1;
    Widget  _radiobox2;
    Widget  _radiobox3;
    Widget  _radiobox4;
    Widget  _range_label;
    Widget  _rowcolumn1;
    Widget  _scope_by_textfield;
    Widget  _scope_down_arrow;
    Widget  _scope_down_toggle;
    Widget  _scope_form;
    Widget  _scope_frame;
    Widget  _scope_info_form;
    Widget  _scope_info_frame;
    Widget  _scope_left_arrow;
    Widget  _scope_main_form;
    Widget  _scope_main_frame;
    Widget  _scope_main_label;
    Widget  _scope_mark_button;
    Widget  _scope_range_textfield;
    Widget  _scope_right_arrow;
    Widget  _scope_up_arrow;
    Widget  _scope_up_toggle;
    Widget  _separator;
    Widget  _speed_ood_frame;




    // These virtual functions are called from the private callbacks (above)
    // Intended to be overriden in derived classes to define actions

    virtual void back_full_order ( Widget, XtPointer );
    virtual void back_half_order ( Widget, XtPointer );
    virtual void back_stnd_order ( Widget, XtPointer );
    virtual void embt_blow_off ( Widget, XtPointer );
    virtual void embt_blow_on ( Widget, XtPointer );
    virtual void flank_order ( Widget, XtPointer );
    virtual void full_order ( Widget, XtPointer );
    virtual void half_order ( Widget, XtPointer );
    virtual void mbt_vents_open ( Widget, XtPointer );
    virtual void mbt_vents_shut ( Widget, XtPointer );
    virtual void o_crs_100s_add ( Widget, XtPointer );
    virtual void o_crse_100s_minus ( Widget, XtPointer );
    virtual void o_crse_10s_add ( Widget, XtPointer );
    virtual void o_crse_10s_minus ( Widget, XtPointer );
    virtual void o_crse_1s_add ( Widget, XtPointer );
    virtual void o_crse_1s_minus ( Widget, XtPointer );
    virtual void o_dpth_1000s_add ( Widget, XtPointer );
    virtual void o_dpth_1000s_minus ( Widget, XtPointer );
    virtual void o_dpth_100s_add ( Widget, XtPointer );
    virtual void o_dpth_100s_minus ( Widget, XtPointer );
    virtual void o_dpth_10s_add ( Widget, XtPointer );
    virtual void o_dpth_10s_minus ( Widget, XtPointer );
    virtual void o_dpth_1s_add ( Widget, XtPointer );
    virtual void o_dpth_1s_minus ( Widget, XtPointer );
    virtual void scope_lower ( Widget, XtPointer );
    virtual void scope_mark ( Widget, XtPointer );
    virtual void scope_raise ( Widget, XtPointer );
    virtual void scope_view_down ( Widget, XtPointer );
    virtual void scope_view_left ( Widget, XtPointer );
    virtual void scope_view_right ( Widget, XtPointer );
    virtual void scope_view_up ( Widget, XtPointer );
    virtual void stnd_order ( Widget, XtPointer );
    virtual void stop_order ( Widget, XtPointer );

    //--- End generated code section

  private: 
    // Array of default resources

    static String      _defaultOodUIResources[];

    // Callbacks to interface with Motif

    static void back_full_orderCallback ( Widget, XtPointer, XtPointer );
    static void back_half_orderCallback ( Widget, XtPointer, XtPointer );
    static void back_stnd_orderCallback ( Widget, XtPointer, XtPointer );
    static void embt_blow_offCallback ( Widget, XtPointer, XtPointer );
    static void embt_blow_onCallback ( Widget, XtPointer, XtPointer );
    static void flank_orderCallback ( Widget, XtPointer, XtPointer );
    static void full_orderCallback ( Widget, XtPointer, XtPointer );
    static void half_orderCallback ( Widget, XtPointer, XtPointer );
    static void mbt_vents_openCallback ( Widget, XtPointer, XtPointer );
    static void mbt_vents_shutCallback ( Widget, XtPointer, XtPointer );
    static void o_crs_100s_addCallback ( Widget, XtPointer, XtPointer );
    static void o_crse_100s_minusCallback ( Widget, XtPointer, XtPointer );
    static void o_crse_10s_addCallback ( Widget, XtPointer, XtPointer );
    static void o_crse_10s_minusCallback ( Widget, XtPointer, XtPointer );
    static void o_crse_1s_addCallback ( Widget, XtPointer, XtPointer );
    static void o_crse_1s_minusCallback ( Widget, XtPointer, XtPointer );
    static void o_dpth_1000s_addCallback ( Widget, XtPointer, XtPointer );
    static void o_dpth_1000s_minusCallback ( Widget, XtPointer, XtPointer );
    static void o_dpth_100s_addCallback ( Widget, XtPointer, XtPointer );
    static void o_dpth_100s_minusCallback ( Widget, XtPointer, XtPointer );
    static void o_dpth_10s_addCallback ( Widget, XtPointer, XtPointer );
    static void o_dpth_10s_minusCallback ( Widget, XtPointer, XtPointer );
    static void o_dpth_1s_addCallback ( Widget, XtPointer, XtPointer );
    static void o_dpth_1s_minusCallback ( Widget, XtPointer, XtPointer );
    static void scope_lowerCallback ( Widget, XtPointer, XtPointer );
    static void scope_markCallback ( Widget, XtPointer, XtPointer );
    static void scope_raiseCallback ( Widget, XtPointer, XtPointer );
    static void scope_view_downCallback ( Widget, XtPointer, XtPointer );
    static void scope_view_leftCallback ( Widget, XtPointer, XtPointer );
    static void scope_view_rightCallback ( Widget, XtPointer, XtPointer );
    static void scope_view_upCallback ( Widget, XtPointer, XtPointer );
    static void stnd_orderCallback ( Widget, XtPointer, XtPointer );
    static void stop_orderCallback ( Widget, XtPointer, XtPointer );

    //--- End generated code section

};
#endif

