
//////////////////////////////////////////////////////////////
//
// Header file for Weaps
//
//    This file is generated by RapidApp
//
//    This class is derived from WeapsUI which 
//    implements the user interface created in 
//    the interface builder. This class contains virtual
//    functions that are called from the user interface.
//
//    When you modify this header file, limit your changes to adding
//    members below the "//--- End generated code section" markers
//
//    This will allow the builder to integrate changes more easily
//
//    This class is a ViewKit user interface "component".
//    For more information on how components are used, see the
//    "ViewKit Programmers' Manual", and the RapidApp
//    User's Guide.
//////////////////////////////////////////////////////////////
#ifndef WEAPS_H
#define WEAPS_H
#include "WeapsUI.h"

//---- End generated headers


//---- Weaps class declaration

class Weaps : public WeapsUI
{

  public:

    Weaps(const char *, Widget);
    Weaps(const char *);
    ~Weaps();
    const char *  className();

    void update();
    //---- End generated code section


  protected:


    // These functions will be called as a result of callbacks
    // registered in WeapsUI

    virtual void port_tube_shoot ( Widget, XtPointer );
    virtual void pt_crs_100s_add ( Widget, XtPointer );
    virtual void pt_crs_100s_minus ( Widget, XtPointer );
    virtual void pt_crs_10s_add ( Widget, XtPointer );
    virtual void pt_crs_10s_minus ( Widget, XtPointer );
    virtual void pt_crs_1s_add ( Widget, XtPointer );
    virtual void pt_crs_1s_minus ( Widget, XtPointer );
    virtual void select_tlam1 ( Widget, XtPointer );
    virtual void select_tlam2 ( Widget, XtPointer );
    virtual void select_tlam3 ( Widget, XtPointer );
    virtual void select_tlam4 ( Widget, XtPointer );
    virtual void select_tlam5 ( Widget, XtPointer );
    virtual void select_tlam6 ( Widget, XtPointer );
    virtual void select_tube1 ( Widget, XtPointer );
    virtual void select_tube2 ( Widget, XtPointer );
    virtual void select_tube3 ( Widget, XtPointer );
    virtual void select_tube4 ( Widget, XtPointer );
    virtual void shoot_tlam ( Widget, XtPointer );
    virtual void st_crs_100s_add ( Widget, XtPointer );
    virtual void st_crs_100s_minus ( Widget, XtPointer );
    virtual void st_crs_10s_add ( Widget, XtPointer );
    virtual void st_crs_10s_minus ( Widget, XtPointer );
    virtual void st_crs_1s_add ( Widget, XtPointer );
    virtual void st_crs_1s_minus ( Widget, XtPointer );
    virtual void stbd_tube_shoot ( Widget, XtPointer );

    //---- End generated code section


  private:

};
#endif

