# ***** ALWAYS leave the following include line ***
include ../../Makefile.lib_pre
include ../../Makefile.exe_pre

# You can change these flags while testing for optimizations
OPT	=
#CFLAGS	=	$(OPT)
#OBJLIST	=

# You can define include directories your code needs here --
#    other than ../include
APPINCDIRS	=	-I/usr/include/Performer -I../../interface/include \
			-I/usr/src/Performer/include

# You can define your own standard include files, if necessary
STDINCS =	../../interface/include/odt.h

# You can define include directories your code needs here --
APPLIBDIRS	=	-L$(BINDIR)lib -L/usr/src/Performer/lib

# You can include your own library flags (i.e. -llib) here --
APPLIBFLAGS	= -lodt$(GL_EXT)$(BIN_EXT) -lmpc -lX11 -lm -lfpe -lC -rpath ./bin/lib/

LIBDEP  =       $(BINDIR)lib/libodt$(GL_EXT)$(BIN_EXT).$(LIB_EXT)

# ***********************************************************************
# ***** ALWAYS list targets and the objects for the targets here *****

TARGETS =       $(BINDIR)odt_test$(GL_EXT)$(BIN_EXT)
OBJECTS	=	odt_test$(GL_EXT)$(BIN_EXT).o


# ***********************************************************************


# ***** ALWAYS leave the following include line ***
include ../../Makefile.exe_post


# ***********************************************************************
# ***** ALWAYS list object file dependencies here

odt_test$(GL_EXT)$(BIN_EXT).o:	odt_test.cc $(STDINCS) $(LIBDEP)

# ***********************************************************************
