// File: <category.h>

/*
 * Copyright (c) 1995,
 *    Naval Postgraduate School
 *    Computer Graphics and Video Laboratory
 *    NPSNET Research Group
 *    npsnet@cs.nps.navy.mil
 *
 *
 *    Permission to use, copy, and modify this software and its
 * documentation for any non-commercial purpose is hereby granted
 * without fee, provided that (i) the above copyright notices and the
 * following permission notices appear in ALL copies of the software
 * and related documentation, and (ii) The Naval Postgraduate School
 * Computer Graphics and Video Laboratory and the NPSNET Research Group
 * be given written credit in your software's written documentation and
 * be given graphical credit on any start-up/credit screen your 
 * software generates.
 *    This restriction helps justify our research efforts to the
 * sponsors who fund our research.
 *
 *    Do not redistribute this code without the express written
 * consent of the NPSNET Research Group. (E-mail communication and our
 * confirmation qualifies as written permission.) As stated above, this 
 * restriction helps justify our research efforts to the sponsors who
 * fund our research.
 *
 *    This software was designed and implemented at U.S. Government
 * expense and by employees of the U.S. Government.  It is illegal
 * to charge any U.S. Government agency for its partial or full use.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS, IMPLIED OR OTHERWISE, INCLUDING WITHOUT LIMITATION, ANY
 * WARRANTY OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.
 * 
 * E-Mail addresses:
 *    npsnet@cs.nps.navy.mil
 *       General code questions, concerns, comments, requests for
 *       distributions and documentation, and bug reports.
 *    npsnet-info@cs.nps.navy.mil
 *       Contact principle investigators.
 *       Overall research project information and funding.
 *       Requests for demonstations.
 *
 * Thank you to our sponsors:  ARL, STRICOM, TRAC, ARPA and DMSO.
 */
/* File:	category.h
 * Description:	DIS Vehicle Categories
 * Revision:	1.0 - 07Jul92
 *
 * Reference:	Military Standard--Protocol Data Units for Entity
 *		Information and Entity Interaction in a Distributed
 *		Interactive Simulation (DIS) (30Oct91)
 *		Appendix H2
 *
 * Author:	John Locke
 *		CS Department, Naval Postgraduate School
 * Internet:	jxxl@taurus.cs.nps.navy.mil
 */


/*	Category is dependant on EntityKind */

#define Category_Other			0

/* U.S. Platforms */

/* U.S. Land */
#define Category_Tank			1
#define		M1_Abrams			1
#define			M1A1_Abrams			1
#define			M1A2				2
#define			M1A1_MineRollers		3
#define			M1A1_MinePlows			4
#define		M60_MBT				2
#define			M60A3_MBT			1
#define		M551_Sheridan			3
#define		M48_Light			4
#define Category_ArmoredFightVeh	2
#define		IFV				1
#define		CFV				2
#define		M2_Bradley			3
#define		M3_Bradley			4
#define		M113				5
#define			M113A2				1
#define			M113A3				2
#define			M113A3_M105_Trailer		3
#define			M981_Fist-V			4
#define			M106A1				5				2
#define		LAV_25				6
#define		LAV_Tow				7
#define		ArmoredFightingVeh	2	
#define		M901A1_Itv				8
#define		M106A1_Mortar_Carrier			9
#define		V-600_Armored_Car			10
#define Category_ArmoredUtilVeh		3
#define		M88_MedRecovery			1
#define			M88A1				1
#define			M88A2				2
#define		M578_LightArmRecovery		2
#define         M901_FistV			3
#define         AVLB				4
#define         M728_Cev			5
#define         M9_ArmoredCombatEarthmover	6
#define         V_500Commando			7	
#define Category_SelfPropelArtillery	4
#define		MLRS				1
#define		M110_8inch			2
#define		M109_155mm			3
#define		GLCM_Launcher			4
#define		PershingLauncher		5
#define Category_TowedArtillery		5
#define		M114_155mm_Howitzer		1
#define		M198_155mm_TowedHowitzer	2
#define		M101_105mm_Howitzer		3
#define		M192_105mm_LightHowitzer	4
#define Category_SmallWheelUtilVeh	6
#define		HUMMV				1
#define		M577				2
#define			M577A1					1
#define         	M577A2					2
#define		FastAttackVehicle		3
#define		M58A3_Mclic			4
#define Category_LargeWheelUtilVeh	7
#define		M352_2_5_Ton			1
#define			M352				1
#define			M352A2				2
#define		M977_HEMTT			2
#define		M978_HEMTT			3
#define		M817				4
#define       	M939                            5
#define         M17_HostedVulcano		6
#define         M985_Hemtt			7
#define         M915                      	8
#define         Cargo                                    1
#define         Ps_Pods                                  2
#define         Shelter                                  3
#define         M1038                           9
#define         M1039				10
#define         M35                             11
#define Category_SmallTrackUtilVeh	8
#define Category_LargeTrackUtilVeh	9
#define		M548				1
#define Category_Mortar			10
#define		M29_81mm_Mortar			1
#define		M224_60mm_LightCompanyMortar	2
#define Category_AmphibAssaultVeh	50
#define		LTVP_7_AmphibAssaultVehicle	1
#define Category_MiscWeaponSys		51
#define		M901_40mm_MachineGun		1
#define		Mk_19_40mm_GrenadeLauncher	2
#define		VulcanAirDefenseSystem_20mm	3

/* U.S. Air */
#define Category_Fighter		1
#define		F_117_Stealth			1
#define			F_117A				1
#define		F_14				2
#define			F_14A				1
#define			F_14B				2
#define			F_14C				3
#define			F_14DF				4
#define		F_16				3
#define			F_16A				1
#define			F_16B				2
#define			F_16C				3
#define			F_16D				4
#define			F_16E				5
#define		F_B_111				4
#define		F_4				5
#define		F_8				6
#define		F_15				7
#define         F_22				8
#define		F_100				9
#define		F_104				10
#define		F_101				11
#define		F_102				12
#define		F_106				13
#define		F_105				14
#define         F_111                      	15
#define		F_A_18				16
#define		EF_111				17
#define		F_5				18
#define Category_Attack			2
#define		A_4				1
#define		A_6				2
#define		A_7				3
#define		A_10				4
#define		A_37				5
#define		EA_6				6
#define			EA_6A				1
#define			EA_6B				2
#define		KA_6				7
#define		AV_8				8
#define			AV_8A				1
#define			AV_8B				2
#define		A_3				9
#define Category_Bomber			3
#define		B_1				1
#define			B_1A				1
#define			B_1B				2
#define		B_2				2
#define                 B-2A				1
#define		B_52				3
#define Category_Cargo			4
#define		C_130				1
#define		C_5				2
#define			C_5A				1
#define		C_141				3
#define		C_135				4
#define		KC_135				5
#define		KC_10				6
#define Category_AntiSubPatrol		5
#define		P_3				1
#define		S_3				2
#define		OV_10				3
#define Category_AttackHelicopter	6
#define		AH_64_Apache				1
#define		AH_1				2
#define                	AH_1G				1
#define                	AH_1S                		2
#define 	       	AH_1W				3
#define        	       	AH_1_Venom			4
#define        	      	RAH_66_Commanche		3
#define Category_UtilityHelicopter	7
#define		UH_1				1
#define		UH_60				2
#define			UH_60A				1
#define			UH_60L				2
#define		H_46				3
#define         S_70       			4
#define Category_CargoHelicopter	50
#define		CH_47				1
#define			CH_47C				1
#define			CH_47D				2
#define		CH_53				2
#define Category_ObservationHelicopter	51
#define		OH_58				1
#define			OH_58C				1
#define			OH_58D				2
#define Category_SeaGoingHelicopter	52
#define		SH_2				1
#define		SH_3				2
#define		SH_60				3
#define			SH_60B				1
#define			SH_60FB				2
#define Category_ElectronicWarfare	53
#define		E_2				1
#define		EA_3				2
#define			EA_3A				1
#define			EA_3B				2
#define		E_6				3
#define			E_6A				1
#define		E_3				4
#define			E_3A				1
#define		E_4				5
#define			E_4A				1
#define			E_4B				2
#define		JSTARS				6
#define Category_UnmannedAirVehicle	54
#define Category_SpyPlanes  			54
#define                SR_71			1
#define                TR_1			2
#define        	       U_2			3
#define Category_SpecialOperations	55
#define 	MH_60				1
#define 		MH_60G				1
#define 		MH_60K				2
#define 	MH_47				2
#define 		MH_47E				1
#define 	MH_53				3
#define 		MH_53J				1
#define 	MH_6				4		

/* U.S. Surface */
#define Category_Carrier		1
#define		Class_Nimitz			1
#define			CVN68_Nimitz			1
#define			CVN69_DwightDEisenhower		2
#define			CVN70_CarlVinson		3
#define			CVN71_TheodoreRoosevelt		4
#define			CVN72_GeorgeWashington		5
#define			CVN73_AbrahamLincoln		6
#define		Class_Enterprise		2
#define			CVN65_Enterprise		1
#define		Class_KittyHawkJFK		3
#define			CV63_KittyHawk			1
#define			CV64_Constellations		2
#define			CV66_America			3
#define			CV67_JohnFKennedy		4
#define		Class_Forrestal			4
#define			CV59_Forrestal			1
#define			CV60_Saratoga			2
#define			CV61_Ranger			3
#define			CV62_Independence		4
#define		Class_Midway			5
#define			CV41_Midway			1
#define			CV43_CoralSea			2
#define Category_CommandShipCruiser	2
#define		Class_BlueRidge			1
#define			LCC19_BlueRidge			1
#define			LLC20_MountWhitney		2
#define		Misc_ConvertedCommandShips	2
#define			AGF11_Coronado			1
#define			AGF3_LaSalle			2
#define Category_GuidedMissileCruiser	3
#define		Class_Ticonderoga		1
#define			CG47_Ticonderoga		1
#define			CG48_Yorktown			2
#define			CG49_Vincennes			3
#define			CG50_ValleyForge		4
#define			CG51_ThomasSGates		5
#define		Class_Virginia			2
#define			CGN38_Virginia			1
#define			CGN39_Texas			2
#define			CGN40_Mississippi		3
#define			CGN41_Arkansas			4
#define		Class_California		3
#define			CGN36_California		1
#define			CGN37_SCarolina			2
#define		Class_Truxtun			4
#define			CGN35_Truxton			1
#define		Class_Belknap			5
#define			CG26_Belknap			1
#define			CG27_JosephusDaniels		2
#define			CG28_Wainwright			3
#define			CG29_Jouett			4
#define			CG30_Horne			5
#define			CG31_Sterett			6
#define			CG32_WHStandley			7
#define			CG33_Fox			8
#define			CG34_Biddle			9
#define		Class_Bainbridge		6
#define			CGN25_Bainbridge		1
#define		Class_Leahy			7
#define			CG16_Leahy			1
#define			CG17_HarryEYarnell		2
#define			CG18_Worden			3
#define			CG19_Dale			4
#define			CG20_RKTurner			5
#define			CG21_Gridley			6
#define			CG22_England			7
#define			CG23_Halsey			8
#define			CG24_Reeves			9
#define		Class_Albany			8
#define			CG10_Albany			1
#define		Class_LongBeach			9		
#define			CGN9_LongBeach			1
#define Category_GuidedMissileDestroyer	4
#define		Class_CharlesFAdams		4
#define        	      	DDG2_CharlesFAdams		1
#define        		DDG3_JohnKing			2
#define        		DDG4_Lawrence			3
#define        		DDG5_CVRicketts		4
#define        		DDG6_Barney			5
#define        		DDG7_HenryBWilson		6
#define        		DDG8_LyndeMcCormick		7
#define        		DDG9_Towers			8
#define        		DDG10_Sampson			9
#define        		DDG11_Sellers			10
#define        		DDG12_Robison			11
#define       	 	DDG13_Hole			12
#define        		DDG14_Buchanan			13
#define        		DDG15_Berkeley			14
#define			DDG15_Berkeley			14
#define			DDG16_JosephStrauss		15
#define			DDG17_Conyngham			16
#define			DDG18_Semmes			17
#define			DDG19_Tattnal			18
#define			DDG20_Goldsborough		19
#define			DDG21_Cochrane			20
#define			DDG22_BenStoddert		21
#define			DDG23_RichardEByrd		22
#define			DDG24_Waddell			23
#define Category_Destroyer		5
#define		Class_Spruance			1
#define			DD963_Spruance			1
#define			DD964_PaulFFoster		2
#define			DD965_Kinkaid			3
#define			DD966_Hewitt			4
#define			DD967_Elliott			5 
#define			DD968_AWRadford			6
#define			DD969_Peterson			7
#define			DD970_Caron			8
#define			DD971_DavidRRay			9
#define			DD972_Olendorf			10
#define			DD973_JohnYoung			11
#define			DD974_ComteDeGrasse		12
#define			DD975_OBrien			13
#define			DD976_Merrill			14
#define			DD977_Briscoe			15
#define			DD978_Stump			16
#define			DD979_Conolly			17
#define			DD980_Moosebrugger		18
#define			DD981_JohnHancock		19
#define			DD982_Nicholson			20
#define			DD983_JohnRodgers		21
#define			DD984_Leftwich			22
#define			DD985_Cushing			23
#define			DD986_HarryWHill		24
#define			DD987_OBannon			25
#define			DD988_Thorn			26
#define			DD989_Deyo			27
#define			DD990_Ingersoll			28
#define			DD991_Fife			29
#define			DD992_Fletcher			30
#define			DD993_Hayler			31
#define Category_GuidedMissileFrigate	6
#define		Class_OliverPerry		1
#define			FFG7_OHPerry			1
#define			FFG8_McInerney			2
#define			FFG9_Wadsworth			3
#define			FFG10_Duncan			4
#define			FFG11_Clark			5
#define			FFG12_GeorgePhillip		6
#define			FFG13_SamEMorison		7
#define			FFG14_Sides			8
#define			FFG15_Estocin			9
#define			FFG16_CliftonSprauge		10
#define			FFG19_JohnAMoore		11
#define			FFG20_Antrim			12
#define			FFG21_Flatley			13
#define			FFG22_Fahrion			14
#define			FFG23_LewisBPuller		15
#define			FFG24_JackWilliams		16
#define			FFG25_Copeland			17
#define			FFG26_Gallery			18
#define			FFG27_MSTisdale			19
#define			FFG28_Boone			20
#define			FFG29_SWGroves			21
#define			FFG30_Reid			22
#define			FFG31_Stark			23
#define			FFG32_JohnLHall			24
#define			FFG33_Jarrett			25
#define			FFG34_AubreyFitch		26
#define			FFG36_Underwood			27
#define			FFG37_Crommelin			28
#define			FFG38_Curts			29
#define			FFG39_Doyle			30
#define			FFG40_Halyburton		31
#define			FFG41_McClusky			32
#define			FFG42_Klakring			33
#define			FFG43_Thatch			34
#define			FFG45_DeWert			35
#define			FFG46_Rentz			36
#define			FFG47_Nicholas			37
#define			FFG48_Vandegrift		38
#define			FFG49_RGBradley			39
#define			FFG50_JesseLTaylor		40
#define			FFG51_Gary			41
#define			FFG52_Carr			42
#define			FFG53_Hawes			43
#define			FFG54_Ford			44
#define			FFG55_Elrod			45
#define			FFG56_Simpson			46
#define			FFG57_ReubenJames		47
#define			FFG58_SamBRoberts		48
#define		Class_Brooke			2
#define			FFG1_Brooke			1
#define			FFG2_Ramsey			2
#define			FFG3_Schofield			3
#define			FFG4_Talbot			4
#define			FFG5_RichardLPage		5
#define			FFG6_JuliusAFurer		6
#define Category_PatrolCraft		7
#define		Class_Pegasus			1
#define			PHM1_Pegasus			1
#define			PHM2_Hercules			2
#define			PHM3_Taurus			3
#define			PHM4_Aquila			4
#define			PHM5_Aries			5
#define			PHM6_Gemini			6
#define		Class_Highpoint			2
#define			PCH1_Highpoint			1
#define		Class_SpecialWarfarePatrolBoat	3
#define			PBM1				1
#define Category_MineCountermeasureShip	8
#define		Type_MSH			1
#define			MSH1				1
#define		Class_Avenger			2
#define			MCM1_Avenger			1
#define			MCM2_Defender			2
#define			MCM3_Sentry			3
#define			MCM4_Champion			4
#define			MCM5_Guardian			5
#define		Class_Acme			3
#define			MSO509_Adroit			1
#define			MSO511_Affray			2
#define		Class_AgileAggressive		4
#define      		MSO427_Constant			1
#define      		MSO433_Engage			2
#define      		MSO437_Enhance			3
#define      		MSO438_Esteem			4
#define      		MSO439_Excel			5
#define      		MSO440_Exploit			6
#define      		MSO441_Exultant			7
#define      		MSO442_Fearless			8
#define      		MSO443_Fidelity			9
#define      		MSO446_Fortify			10
#define      		MSO448_Illusive			11
#define      		MSO449_Impervious		12
#define      		MSO455_Implicit			13
#define      		MSO456_Inflict			14
#define      		MSO464_Pluck			15
#define      		MSO488_Conquest			16
#define      		MSO489_Gallant			17
#define      		MSO490_Leader			18
#define      		MSO492_Pledge			19
#define Category_DockLandingShip	9
#define		Class_WhidbeyIsland		1
#define			LSD1_WhidbeyIsland		1
#define			LSD2_Germantown			2
#define		Class_Anchorage			2
#define			LSD36_Anchorage			1
#define			LSD37_Portland			2
#define			LSD38_Pensacola			3
#define			LSD39_MountVernon		4
#define			LSD40_FortFisher		5
#define		Class_Thomaston			3
#define			LSD28_Thomaston			1
#define			LSD29_PlymouthRock		2
#define			LSD30_FortSnelling		3
#define			LSD31_PointDefiance		4
#define			LSD32_SpeigelGrove		5
#define			LSD33_Alamo			6
#define			LSD34_Hermitage			7
#define			LSD35_Monticello		8
#define Category_TankLandingShip	10
#define		Class_Newport			1
#define			LST1179_Newport			1
#define			LST1180_Manitowac		2
#define			LST1181_Sumter			3
#define			LST1182_Fresno			4
#define			LST1183_Peoria			5
#define			LST1184_Frederrick		6
#define			LST1185_Schenectady		7
#define			LST1186_Cayuga			8
#define			LST1187_Tuscaloosa		9
#define			LST1188_Saginaw			10
#define			LST1189_SanBernardino		11
#define			LST1190_Boulder			12
#define			LST1191_Racine			13
#define			LST1192_SpartanburgCounty	14
#define			LST1193_FairfaxCounty		15
#define			LST1194_LaMoureCounty		16
#define			LST1195_BarbourCounty		17
#define			LST1196_HarlanCounty		18
#define			LST1197_BarnstableCounty	19
#define			LST1198_BristolCounty		20					
#define		Class_DeSotoCounty		2
#define			LST1173_SuffolkCounty		1
#define			LST1177_LorrainCounty		2
#define			LST1178_WoodCounty		3
#define		Class_TerreboneParish		3
#define			LST1158_TiogaCounty		1
#define			LST1160_TraverseCounty		2
#define			LST1162_WahkiakumCounty	3
#define			LST1163_WaldoCounty		4
#define			LST1164_WalworthCounty		5
#define			LST1165_WashoeCounty		6
#define Category_LandingCraft		11
#define		Type_LCAC			1
#define			LCAC				1
#define		Class_LCU_1610			2
#define			LCU_1616to1679			1
#define Category_Frigate		50
#define		Class_Knox			1
#define			FF1052_Knox			1
#define			FF1053_Roark			2
#define			FF1054_Gray			3
#define			FF1055_Hepburn			4
#define			FF1056_Connole			5
#define  		FF1057_Rathburne		6
#define			FF1058_Meyerkord		7
#define			FF1059_WSSims			8
#define			FF1060_lang			9
#define			FF1061_Patterson		10
#define			FF1062_Whipple			11
#define			FF1063_Reasoner			12
#define			FF1064_Lockwood			13
#define			FF1065_Stein			14
#define			FF1066_MarvinShields		15
#define			FF1067_FHammond			16
#define			FF1068_Vreeland			17
#define			FF1069_Bagley			18
#define			FF1070_Downes			19
#define			FF1071_Badger			20
#define 		FF1072_Blakely			21
#define			FF1073_REPeary			22
#define			FF1074_HaroldEHolt		23
#define			FF1075_Trippe			24
#define			FF1076_Fanning			25
#define			FF1077_Ouellet			26
#define			FF1078_JosephHewes		27
#define			FF1079_Bowen			28
#define			FF1080_Paul			29
#define			FF1081_Aylwin			30
#define			FF1082_EMontgomery		31
#define			FF1083_Cook			32
#define			FF1084_McCandless		33
#define			FF1085_DBBeary			34
#define			FF1086_Brewton			35
#define			FF1087_Kirk			36
#define			FF1088_Barbey			37
#define			FF1089_JLBrown			38
#define			FF1090_Ainsworth		39
#define			FF1091_Miller			40
#define			FF1092_TCHart			41
#define			FF1093_Capodanno		42
#define			FF1094_Pharris			43
#define			FF1095_Truett			44
#define			FF1096_Valdez			45
#define			FF1097_Moinester		46	
#define		Class_Garcia			2
#define			FF1040_Garcia			1
#define			FF1041_Bradley			2
#define			FF1043_EMcDonnell		3
#define			FF1044_Brumby			4
#define			FF1045_Davidson			5
#define			FF1047_Voge			6
#define			FF1048_Sample			7
#define			FF1049_Koelsch			8
#define			FF1050_AlbertDavid		9
#define			FF1051_OCallahan		10
#define		Class_Bronstein			3
#define			FF1037_Bronstein		1
#define			FF1038_McCloy			2
#define Category_Battleship		51
#define		Class_Iowa			1
#define			BB61_Iowa			1
#define			BB62_NewJersey			2
#define			BB63_Missouri			3
#define Category_HeavyCruiser		52
#define		Class_DesMoines			1
#define			CA134_DesMoines			1
#define			CA139_Salem			2
#define Category_DestroyerTender	53
#define		Class_SamGompers_Yellowstone	1
#define			AD37_SamualGompers		1
#define			AD38_PugetSound       		2
#define			AD41_Yellowstone		3
#define			AD42_Acadia			4
#define			AD43_CapeCod			5
#define			AD44_Shenandoah			6
#define		Class_Dixie			2
#define			AD15_Prarie			1
#define			AD18_Sierra			2
#define			AD19_Yosemite			3
#define Category_AmphibousAssaultShip	54
#define		Class_Tarawa			1
#define			LHA1_Tarawa			1
#define			LHA2_Saipan			2
#define			LHA3_BelleauWood		3
#define			LHA4_Nassau			4
#define			LHA5_Peleliu			5
#define		Class_IwoJima			2
#define			LPH2_IwoJima	       		1
#define			LPH3_Okinawa			2
#define			LPH7_Guadalcanal		3
#define			LPH9_Guam			4
#define			LPH10_Tripoli			5
#define			LPH11_NewOrleans		6
#define			LPH12_Inchon			7			
#define		Class_Wasp			3
#define			LDH1_Wasp			1
#define Category_AmphibiousCargoShip	55
#define		Class_Charleston		1
#define			LKA113_Charleston		1
#define			LKA114_Durham			2
#define			LKA115_Mobile			3
#define			LKA116_StLoui			4
#define			LKA117_ElPaso			5
#define Category_AmphibiousTransportDock56
#define		Class_Austin			1
#define			LPD4_Austin			1
#define			LPD5_Ogden			2
#define			LPD6_Duluth			3
#define			LPD7_Cleveland			4
#define			LPD8_Dubuque			5
#define			LPD9_Denver			6
#define			LPD10_Juneau			7
#define			LPD12_Shreveport		8
#define			LPD13_Nashville			9
#define			LPD14_Trenton			10
#define			LPD15_Ponce			11
#define		Class_Raleigh			2
#define			LPD1_Raleigh			1
#define			LPD2_Vancouver			2
#define Category_AmmunitionShip       	57
#define		Class_Kilauea			1
#define			T_AE26_Kilauea			1
#define			AE27_Butte			2
#define			AE28_SantaBarbara		3
#define			AE29_MountHood			4
#define			AE32_Flint			5
#define			AE33_Shasta			6
#define			AE34_MountBake			7
#define			AE35_Kiska			8
#define		Class_Suribachi			2
#define			AE21_Suribachi			1
#define			AE22_MounaKea			2
#define			AE23_Nitro			3
#define			AE24_Pyro			4
#define			AE25_Haleakala			5
#define Category_CombatStoresShip	58
#define		Class_ExBritish       		1
#define			T_AFS8_Sirius			1
#define			T_AFS9_Spica			2
#define			T_AFS10_Saturn			3
#define		Class_Mars			2
#define			AFS1_Mars			1
#define			AFS2_Sylvania			2
#define			AFS3_NiagraFalls		3
#define			AFS4_WhitePlains		4
#define			AFS5_Concord			5
#define			AFS6_SanDiego			6
#define			AFS7_SanJose			7
#define Categroy_Surtass		59
#define		Class_Stalward			1
#define			T_Agos1_Stalwart		1
#define			T_Agos2_Contendar		2
#define			T_Agos3_Vindicator		3
#define			T_Agos4_Triumph			4
#define			T_Agos5_Assurance		5
#define			T_Agos6_Persistent		6
#define			T_Agos7_Indomitable		7
#define			T_Agos8_Prevail			8
#define			T_Agos9_Assertive		9
#define			T_Agos10_Invincible		10
#define			T_Agos11_Audacious		11
#define			T_Agos12_Bold			12
#define			T_Agos13_Adventurous		13
#define			T_Agos14_Worthy			14
#define			T_Agos15_Titan			15
#define			T_Agos16_Capable		16
#define			T_Agos17_Tenacious		17
#define			T_Agos18_Relentless		18
#define 	Class_SwathS			2
#define			T_Agos1_Victorious		19
#define			T_Agos2_Able			20
#define			T_Agos3_Effective		21
#define			T_Agos4_Loyal			22
#define		Class_SwathL			3
#define			T_Agos1Impeccable		23
#define Categroy_FastCombatSupportship	60
#define		Class_Sacramento		1
#define			AOE1_Sacramento			1
#define			AOE2_Camden			2
#define			AOE3_Seattle			3
#define			AOE4_Detroit			4
#define		Class_Supply			2
#define			AOE6_Supply			1
#define			AOE7_Rainier			2
#define			AOE8_Arctic			3
/* U.S. Subsurface */
#define	Category_SrategicMissleSub	1
#define		Class_Ohio			1
#define			SSBN726_Ohio			1
#define			SSBN727_Michigan		2
#define			SSBN728_Florida			3
#define			SSBN729_Georgia			4
#define			SSBN730_HLJackson		5
#define			SSBN731_Alabama			6
#define			SSBN732_Alaska			7
#define			SSBN733_Nevada			8
#define		Class_LafayetteBenFranklin	2
#define			SSBN616_Lafayette		1
#define			SSBN617_AlexanderHamilton	2
#define			SSBN619_AndrewJackson		3
#define			SSBN620_JohnAdams		4
#define			SSBN622_JamesMonroe		5
#define			SSBN623_NathanHale		6
#define			SSBN624_WoodrowWilson		7
#define			SSBN625_HenryClay		8
#define			SSBN626_DanielWebster		9
#define			SSBN627_JamesMadison		10
#define			SSBN628_Tecumseh		11
#define			SSBN629_DainielBoone		12
#define			SSBN630_JohnCCalhoun		13
#define			SSBN631_UlyssesSGrant		14
#define			SSBN632_Von_Steuben		15
#define			SSBN633_CasimirPulaski		16
#define			SSBN634_StonewallJackson	17
#define			SSBN635_SamRayburn		18
#define			SSBN636_NathanielGreene		19
#define			SSBN640_Benfranklin		20
#define			SSBN641_SimonBolivar		21
#define			SSBN642_Kamehameha		22
#define			SSBN643_GeorgeBancroft		23
#define			SSBN644_LewisandClark		24
#define			SSBN645_JamesKPolk		25
#define			SSBN654_GeorgeCMarshall		26
#define			SSBN655_HenryL.Stimson		27
#define			SSBN656_GreogeWCarver		28
#define			SSBN657_FrancisScottKey		29
#define			SSBN658_MarianoGVallejo		30
#define			SSBN659_WillRogers		31					
#define	Category_AttackSub		2
#define		Class_LosAngeles		1
#define			SSN688_LosAngeles		1
#define			SSN689_BatonRouge		2
#define			SSN690_Philadelphia		3
#define			SSN691_Memphis			4
#define			SSN692_Omaha			5
#define			SSN693_Cincinnati		6
#define			SSN694_Groton			7
#define			ssn695_Birmingham		8
#define			SSN696_NewYorkCity		9
#define			SSN697_Indianapolis		10
#define			SSN698_Bremerton		11
#define			SSN699_Jacksonville		12
#define			SSN700_Dallas			13
#define			SSN701_LaJolla			14
#define			SSN702_Phoenix			15
#define			SSN703_Boston			16
#define			SSN704_Baltimore		17
#define			SSN705_CorpusChirsti		18
#define			SSN706-Albuquerque		19
#define			SSN707_Portsmoouth		20
#define			SSN708_MinneapolisStPaul	21
#define			SSN709_HymanGRickover		22
#define			SSN710_Augusta			23
#define			SSN711_SanFrancisco		24
#define			SSN712_Atlanta			25
#define			SSN713_Huoston			26
#define			SSN714_Norfork			27
#define			SSN715_Buffalo			28
#define			SSN716_SaltLakeCity		29
#define			SSN717_Olympia			30
#define			SSN718_Honolulu			31
#define			SSN719_Providence		32
#define			SSN720_Pittsburgh		33
#define			SSN750_NewportNews		34
#define		Class_GlenPLipscomb		2
#define			SSN685_GlenPLipscomb		1
#define		Class_Narwhal			3
#define			SSN671_Narwhal			2
#define		Class_Sturgeon			4
#define			SSN637_Sturgeon			1
#define			SSN638_Whale			2
#define			SSN639_Tautog			3
#define			SSN646_Grayling			4
#define			SSN647_Pogy			5
#define			SSN648_Aspro			6
#define			SSN649_Sunfish			7
#define			SSN650_Pargo			8
#define			SSN651_Queeenfish		9
#define			SSN652_Puffer			10
#define			SSN653_Ray			11
#define			SSN660_SandLance		12
#define			SSN661_Lapon			13
#define			ssn662_Guenard			14
#define			ssn663_Hammerhead		15
#define			SSN664_SeaDevil			16
#define			SSN665_Guitarro			17
#define			SSN666_Hawkbill			18
#define			SSN667_Bergall			19
#define			SSN668_Spadefish		20
#define			SSN669_Seahorse			21
#define			SSN670_Finback			22
#define			SSN672_Pintado			23
#define			SSN673_FlyingFish		24
#define			SSN674_Trepang			25
#define			SSN675_Bluefish			26
#define			SSN676_Billfish			27
#define			SSN677_Durm			28
#define			SSN678_Archerfish		29
#define			SSN679_Silversides		30
#define			SSN680_WilliamHBates		31
#define			SSN681_Batfish			32
#define			SSN682_Tunny			33
#define			SSN683_Parche			34
#define			SSN684_Cavalla			35
#define			SSN686_LMendelRivers		36
#define			SSN687_RBRussell		37		
#define		Class_Permit			5
#define			SSN594_Permit			1
#define			SSN595_Plunger			2
#define			SSN596_Barb			3
#define			SSN603_Pollack			4
#define			SSN604_Haddo			5
#define			SSN605_Jack			6
#define			SSN606_Tinosa			7
#define			SSN607_Dace			8
#define			SSN612_Guardfish		9
#define			SSN613_Flasher			10
#define			SSN614_Greenling		11
#define			SSN615_Gato			12
#define			SSN621_Haddock			13			
#define		Class_EthanAllen		6
#define			SSN609_SamHuston		1
#define			SSN610_ThomasAEdison		2
#define			SSN611_JohnMarshall		3
#define			SSN712_ThomasJefferson		4
#define		Class_Skipjack			7
#define			SSN585_Skipjack			1
#define			SSN588_Scamp			2
#define			SSN590_Sculpin			3
#define			SSN591_Shark			4
#define			SSN592_Snook			5
#define		Class_Barbel			8
#define			SSN580_Barbel			1
#define			SSN581_Blueback			2
#define			SSN582_Bonefish			3
#define		Class_GeorgeWashington		9
#define			SSN598_GeorgeWashington		1
#define			SSN599_PatrickHenry		2
#define			SSN601_RobertELee		3
#define		Class_Tullibee			10
#define			SSN597_Tullibee			1
#define		Class_Triton			11
#define			SSN586_Triton			1
#define		Class_Skate			12
#define			SSN578_Skate			1
#define			SSN579_Swordfish		2
#define			SSN583_Sargo			3
#define			SSN584_seadragon		4
#define		Class_Seawolf			13
#define			SSN575_Seawolf			1
#define	Category_ReasearchMiscSub	50
#define		Class_Darter			1
#define			SSN576_Darter			1
#define		Class_Dolphin			2
#define			AGSS555_Dolphin			1
#define	Category_UnmannedUnderwaterVeh	51
#define		Mine_Search			1
#define			CSDDraperLabUUV			1		

/* U.S. Space */
#define	Category_MannedPlatform		1
#define		Space_Shuttle			1
#define			SS_Atlantis			1
#define			SS_Discovery			2
#define			SS_Columbia			3
#define			SS_Endeavor			4
#define		Space_Station			2
#define			Freedom				1	
#define	Category_UnmannedPlatform	2
#define		Satellite			1

/**************************************************************************/
/* Soviet Platforms */

/* U.S.S.R. Land */
/*	Category_Tank */
#define		T80_MBT				1
#define		T72_MBT				2
#define			T_72				1
#define			T_72M				2
#define		T64_MBT				3
#define		T62_MBT				4
#define		T54_MBT				5
#define		T55_MBT				6
#define		T10_HeavyTank			7
#define		PT76_AmphibiousLightTank	8
/*	Category_ArmoredFightVeh */
#define		BMP1				1
#define			BMP1K				1
#define		BMP2				2
#define		BRDM1_ReconVeh			3
#define		BRDM2_ReconVeh			4
#define			ATGM_AT4			1
#define			ATGM_AT5			2
#define		BTR40_ReconVeh			5
#define		BTR153_APC			6
#define		MTLB_TrackVeh			7
#define		BTR_60				8
#define		BTR50_AmphibTrackAPC		9
#define		ACRV2_CmdReconVeh		10
#define		BND_AirborneFireSptVeh		11
#define		BTR_70				12
#define		BTR_80				13
#define		BMP_3				14
#define		BMD_2				15
/*  ArmoredUtilityVehicle*/	      
#define		BTS2_ArmoredRecovVeh		1
#define		MTP_MaintenanceVeh		2
#define		IMR2_CombatEngrVeh		3
#define		IPR_AmphibEngrVeh		4
/*	Category_SelfPropelArtillery */
#define		M1973_152mmSPGun		1			
#define		M1974_122mmSpHowitzer		2
#define		M1981_152mmSPGun		3
#define		SPGun_2S7_203mmSPGun		4
#define		ASU85_AirborneAssltGun		5
#define		Frog3_RocketLauncher		6
#define		Frog4_RocketLauncher		7
#define		Frog5_RocketLauncher		8
#define		Frog7_RocketLauncher		9
#define		SS1_ScudMissleLauncher		10
#define		SS12_MediumRangeMissle		11
#define		BM14_140mmRocketLauncher	12
#define		BM21_122mmRocketLauncher	13
#define		M1975_120mmRocketLauncher	14
#define		BM24_240mmRocketLauncher	15
#define		BM25_250mmRocketLauncher	16
#define		BM27_220mmRocketLauncher	17
#define		ZSU_234Quad23mmAA		18
#define		SA_6Sam				19
#define		SA_9Sam				20
#define		SA_13Sam			21
#define		SPGun_2S6			22
/*	Category_TowedArtillery */
#define		S23_180mmFieldGun		1
#define		M1976_152mmFieldGun		2
#define		D20_152mmGunHowitzer		3
#define		D30_122mmGunHowitzer		4
#define		M46_130mmFieldGun		5
#define		D30_FieldHowitzer		6
#define		M1955_T12Gun			7
#define		D44andSD44Gun			8
#define		M1966_76pt2mmMountainGun	9
#define		M1965_140mmRocketLauncher	10
/*	Category_SmallWheelUtilVeh */
#define		GAZ69_LightTruck		1
#define		UAZ469_LightTruck		2
#define		MAV_LgtAmphibTruck		3
/*	Category_LargeWheelUtilVeh */
#define		PZM2_DiggingMachine		1
#define		BAV_AmphibTransport		2
#define		KrAZ255B_Truck			3
#define		ZIL131_Truck			4
#define		ZIL151_Truck			5
#define		ZIL157_Truck			6
#define		GAZ63_Truck			7
#define		GAZ66_Truck			8
#define		Ural375_Truck			9
#define		Kamaz_4310			10
#define		Ural_4320			11
#define		Uaz_3151			12
#define		Kraz_255BtRUCk			13
/*	Category_SmallTrackedUtilityVeh*/	
/*	Category_LargeTrackedUtilityVehicle*/	
#define		PTSAmphibTransport		1
/*	Category_Mortar*/				
#define		M1937_82mmMortar		1
#define		M1943_120mmMortar		2
#define		M1953_160mmMortar		3
#define		M1952_240mmMortar		4
#define		AM2B9_82mmAutomaticMortar	5
#define		SP_2S4_240mmMortar		6


/* U.S.S.R. Air */
/*	Category_Figthe	*/				
#define		MIG31_Foxhound			1
#define		MIG29_Fulcrum			2
#define		SU27_Flanker			3
#define		MIG25_Foxbat			4
#define		MIG23_Flogger_b			5
#define		MIG21_Fishbed			6
#define		MIG19				7
#define		MIG17				8
#define		SU9_Fishpot			9
#define		SU15_Flagon			10
#define		TU128_Fiddler			11
#define		Yak25				12
#define		Yak28_Firebar			13
#define		MIG_27_Flogger			14
/*	Category_Attack	*/ 				
#define		MIG27_FloggerD1			1
#define		SU7				2
#define		SU11				3
#define		SU17_Fitter			4
#define		SU20_FitterC			5
#define		SU22_FitterJ			6
#define		SU24_Fencer			7
#define		SU25_Frogfoot			8
#define		Yak27R				9
#define		Yak36_Forger			10
#define		Yak38_Forger			11
/*	Category_Bomber */		
#define		TU160_Blackjack			1
#define		TU16_Badger			2
#define		TU26_Backfire			3
#define		TU22_Blinder			4
#define		TU95_TU142_Bear			5
#define		M4_Bison			6
/*	Category_Cargo */				
#define		An124_Condor			1
#define		An22_Cock			2
#define		II76_Candid			3
#define		An12_Cub			4
#define		An24_Coke			5
#define		An26_Curl			6
#define		An32_Cline			7
#define		An72_Coaler			8
#define		AN225_Cossack			9
#define		M12_Amphib			10
/*	Category_AntiSubPatrol	*/		
#define		II38_May			1
#define		Be12_Mail			2
#define		Tu126_Moss			3
/*	Category_AttackHelicopter */		
#define		Mi28_Havoc			1
#define		Mi24_Hind			2
#define			Mi24_D				1
#define			Mi24_F				2
#define			Mi24_E				3				
#define		Ka_50_Hokum			3
/*	Category_UtilityHelicopter */		
#define		Mi8_Hip				1
#define		Mi14_Haze			2
#define		Mi26_Halo			3
#define		Mi6_Hook			4
#define		Mi2_Hoplite			5
#define		Mi4_Hound			6
#define		Mi10_Harke			7
#define		Ka25_Hormone			8
#define		Ka27_Helix			9

/* U.S.S.R. Surface */
/*	Category_Carrier */
#define		Class_Kiev			1
#define			Kiev				1
#define			Minsk				2
#define			Novorossiysk			3
#define			Kharkov				4
#define		Class_Moskova			2
#define			Moskova				1
#define			Lenningrad			2
/*	Category_GuidedMissileCruiser */
#define		Class_Krasina			1
#define		Class_Kirov			2
#define			Kirov				1
#define		Class_Kara			3
#define			Nikolayev			1
#define			Ochakov				2
#define			Kerch				3
#define			Azov				4
#define			Petropavlovsk			5
#define			Tashkent			6
#define			Tallinn				7
#define		Class_KrestaII			4
#define			Kronshtadt			1
#define			Adrmiral_Isakov			2
#define			Admiral_Nakhimov		3
#define			Marshal_Voroshilov		4
#define			Admiral_Oktyabrskiy		5
#define			Admiral_Isachenkov		6
#define			Marshal_Timoshenko		7
#define			Vasiliy_Chepayev		8
#define			Admiral_Ymashev			9
#define		Class_KrestaI			5
#define			Admiral_Zozulya			1
#define			Vladivostok			2
#define			Viste_Admiral_Drozd		3
#define			Sevatstopol			4
#define		Class_Kynda			6
#define			Groznyy				1
#define			Admiral_Fokin			2
#define			Admiral_Golovko			3
#define			Varyag				4
#define		Class_GMC_Sverdlov		7
#define			Dzerzhinskiy			1
#define	Category_CommandCruiser		3
#define		Class_ConvertedSverdlov		1
#define			Adrmiral_Senyavin		1
#define			Zhdanov				2
/*	Category_GuidedMissileDestroyer */
#define		Class_Udaloy			1
#define			Udaloy				1
#define			Viste_Admiral_Kulakov		2
#define		Class_Sovremennyy		2
#define			Sovremennyy			1
#define			Otchayannyy			2
#define		Class_ModifiedKashin		3
#define			Ognevoy				1
#define			Slavnyy				2
#define			Sderzhandoyy			3
#define			Smelyy				4
#define			Smyshlennyy			5
#define			Stroynyy			6
#define		Class_Kashin			4
#define			Komsomolets_Ukrainyy		1
#define			Krasnyy_Kavkaz			2
#define			Krasnyy_Krym			3
#define			Obraztsovyy			4
#define			Odarennyy			5
#define			Provornyy			6
#define			Reshitelnyy			7
#define			Skoryy				8
#define			Semtlivvy			9
#define			Soobrazitelnyy			10
#define			Sposobnyy			11
#define			Steregushchiy			12
#define			Storogiy			13
#define		Class_Kanin			5
#define			Boikiy				1
#define			Derzkiy				2
#define			Gnevnyy				3
#define			Gordyy				4
#define			Gremyashchiy			5
#define			Upornyy				6
#define			Zhguchiy			7
#define			Zorkiy				8
#define		Class_ModifiedKildin		6
#define			Bedovy				1
#define			Neulovimyy			2
#define			Prozorlivyy			3
#define		Class_Kidlin			7
#define			Neuderzhimyy			1
#define		Class_SAMKotlin			8
#define			Bravyy				1
#define			Nakhodchivyy			2
#define			Nastochivyy			3
#define			Nesokrushimyy			4
#define			Skromnyy			5
#define			Skrytnyy			6
#define			Soznatel_nyy			7
#define			Vozbuzhdennyy			8
/*	Category_Destroyer */
#define		Class_Kotlin			1
#define			Besslednyy			1
#define			Blagorodnyy			2
#define			Blestyashchiy			3
#define			Burlivyy			4
#define			Byvalyy				5
#define			Dal'nevotochnyy			6
#define			D_Komsomolets			7
#define			Moskovskiy			8
#define			Naporistiy			9
#define			Plamennyy			10
#define			Speshnyy			11
#define			Spokoynyy			12
#define			Svedushchiy			13
#define			Svetlyy				14
#define			Veskiy				15
#define			Vdokhnovenny			16
#define			Vozmushchyennyy			17
#define			Vyderzhannyy			18
#define			Vyzyvayushchiy			19			
#define Category_Skory				2
#define			Bezuderzhnyy			1
#define			Ogennyy				2
#define			Ostorozhny			3
#define			Ozhestochennyy			4
#define			Ozhivlenny			5
#define			Serdity				6
#define			Smotryashy			7
#define			Solidny				8
#define			Sokrushitelnyy			9
#define			Sovershennyy			10
#define			Statny				11
#define			Stepenny			12
#define			Stokyky				13
#define			Stermitelny			14
#define			Surovy				15
#define			Svobdny				16
#define			Vdumchivy			17
#define			Vnimatelny			18
#define			Vrazumitelny			19			
/*	Category_GuidedMissileFrigate */
#define		Class_KrivakI			1
#define			Bditel_nyy			1
#define			Bezurkoriznenyy			2
#define			Bezzevetnity			3
#define			Bodryy				4
#define			Deyatel'nyy			5
#define			Doblestnyy			6
#define			Dostoynyy			7
#define			Druzhnyy			8
#define			Ladnyy				9
#define			Leningradskiy			10
#define			K_Komsomolets			11
#define			Letuchiy			12
#define			Pytlivyy			13
#define			Razumnyy			14
#define			Razyashchiy			15
#define			Retivyy				16
#define			Sil'nyy				17
#define			Stroozhevoy			18
#define			Svirepyy			19
#define			Zadornyy			20
#define			Zharkyy				21
#define		Class_KrivakII			2
#define			Bessmenny			1
#define			Gordelivyy			2
#define			Gromkiy				3
#define			Grozyashchiy			4
#define			Neukrotimyy			5
#define			Pitlivyy			6
#define			Razitel_nyy			7
#define			Revosnttnyy			8
#define			Reskiy				9
#define			Rezvyy				10
#define			R_hanyy				11
/*	Category_PatrolCraft */
#define		Class_Matka			1
#define		Class_Sarancha			2
#define		Class_OSAI			3
#define		Class_OSAII			4
#define		Class_Turya			5
#define		Class_Shershen			6
#define		Class_Babochka			7
#define		Class_Zhuk			8
#define		Class_Slepen			9
#define		Class_Stenka			10
#define		Class_Pchela			11
#define		Class_SO1			12
/*	Category_MineCountermeasureShip */
#define		Class_Alesha			1
#define		Class_NatyaI			2
#define		Class_NatyaII			3
#define		Class_Yurka			4
#define		Class_T43			5
#define		Class_Sonya			6
#define		Class_Zhenya			7
#define		Class_VanyaI			8
#define		Class_VanyaII			9
#define		Class_Sasha			10
#define		Class_Yevgenya			11
/*	Category_DockLandingShip */
#define		Class_IvanRogov			1
#define			Ivan_Rogov			1
#define			AleksanderNikolay		2
/*	Category_TankLandingShip */
#define		Class_Ropucha			1
#define		Class_Alligator			2
#define			AleksandrTortsev		1
#define			DonetskiyShakhter		2
#define			KrasnayaPresnya			3
#define			KrymskiyKom			4
#define			Nikolay_Fil_Chenkov		5
#define			Nikolay_Vilkov			6
#define			Nikolay_Obyekov			7
#define			Petr_I1_Ichyev			8
#define			Sergei_Lazo			9
#define			Tomskiy				10
#define			Voronezhkiy			11		
#define		Class_Polnocny			3
/*	Category_LandingCraft */	
#define		Class_Lebdc			1
#define		Class_Aist			2
#define		Class_Gus			3
#define		Class_Vydra			4
#define		Class_Ondatra			5
#define		Class_T4			6
#define	Category_AntiSubmarineFrigate	50
#define		Class_GrishaI			1
#define		Class_GrishaII			2
#define		Class_GrishaIII			3
#define		Class_MirkaI			4
#define		Class_MirkaII			5
#define		Class_PetyaI			6
#define		Class_PetyaII			7
#define		Class_Riga			8	
#define			Astrakhan_skiyKom		1
#define			Arkhangel_skiyKom		2
#define			Bars				3
#define			Barsuk				4
#define			Bobr				5
#define			Buyvol				6
#define			Byk				7
#define			Gepard				8
#define			Giena				9
#define			Kobchik				10
#define			Komsomolets_Gruziy		11
#define			Komsomolets_Litviy		12
#define			Krasnodarskiy			13
#define			Kunitsa				14
#define			Leopard				15
#define			Lev				16
#define			Lisa				17
#define			Medved				18
#define			Pantera				19
#define			Rys_Rosomakha			20
#define			Shakal				21
#define			Tirg				22
#define			Turman				23
#define			Volk				24
#define			Voron				25
#define			Yaguar				26			
#define		Class_Koni			9
#define			TimofeyUl_yantsev		1
#define	Category_GuidedMissleCorvette	51
#define		Class_TarantulI			1
#define		Class_TarantulII		2
#define		Class_NanuchkaI			3
#define		Class_NanuchkaIII		4
#define	Category_AntiSubmarineCorvette	52
#define		Class_Pauk			1
#define		Class_Poti			2
#define		Class_T58			3
#define			Dzerzhinskiy			1
#define			KaliningradKomsomolets		2
#define			KomsomoletsLatviy		3
#define			Malakhit			4
#define			SovietskiyPogranichinik		5
#define	Category_LightCruiser		53
#define		Class_LC_Sverdlov			1
#define			Admiral_Lazarev			1
#define			Admiral_Ushakov			2
#define			Alekzandr_Nevskiy		3
#define			Alekzandr_Suvorov		4
#define			Dmitriy_Pozharskiy		5
#define			Mikhail_Kutuzov			6
#define			Murmansk			7
#define			Oktyabrskaya			8
#define			Sverdlov			9			
/* U.S.S.R. Subsurface */
/*	Category_SrategicMissleSub */
#define		Class_Typhoon			1
#define		Class_DeltaIV			2
#define		Class_DeltaIII			3
#define		Class_DeltaII			4
#define		Class_DeltaI			5
#define		Class_YankeeII			6
#define		Class_YankeeI			7
#define		Class_HotelIII			8
#define		Class_HotelII			9
#define		Class_GolfV			10
#define		Class_GolfII			11
/*	Category_AttackSub */
#define		Class_OscarII_SSGN		1
#define		Class_OscarI_SSGN		2
#define		Class_Papa_SSGN			3
#define		Class_CharlieII_SSGN		4
#define		Class_CharlieI_SSGN		5
#define		Class_EchoII_SSGN		6
#define		Clas_EchoI_SSN			7
#define		Class_VictorII_SSGN		8
#define		Class_YankeeConversion_SSGN	9
#define		Class_YankeeNotch_SSN		10
#define		Class_WhiskeyLongBin_SSG	11
#define		Class_Juliet_SSG		12
#define		Class_Sierra_SSN		13
#define		Class_Alfa_SSN			14
#define		Class_AlfaImproved_SSN		15
#define		Class_VictorIII_SSN		16
#define		Class_VictorI_SSN		17
#define		Class_November_SSN		18
#define		Class_Kilo_SS			19
#define		Class_Tango_SS			20
#define		Class_Foxtrot_SS		21
#define		Class_Romeo_SS			22
#define		Class_Whiskey_SS		23
#define		Class_Akula_SSN			24
#define		Class_Mike_SSN			25
#define		Class_ZuluIV_SS			26

/* U.S.S.R. Space */
/*	Category_MannedPlatform */	
/*	Space_Shuttle  	*/		
#define			Buran				1
#define		SpaceStation			1
#define			Mir				1
/*	Category_UnmannedPlatform */		
/*	Satellite */     		

/* U.K. Land */
/*	Category_Tank */				
#define		Chieftain_MBT			1
#define		Centurion_MBT			2
#define		Challenger_MBT			3
#define		MK7_MBT				4
#define		FV100_ScorpionLightTank		5
/*	Category_ArmoredFightingVehicle */      	
#define		FV432_APC			1
#define		FG103_SpartanAPC		2
#define		FV601_Saladin			3
#define		FV107_Scimitar			4
#define		FV105_Sultan			5
#define		FV603_Saracen			6
#define		MCV80_CombatVehicle		7
/*	Category_ArmoredUtililityVehicle */	
#define		AT60_ArmoredTransportVehicle	1
/*	Category_SelfPropelledArtillery */	
#define		Abbot_105mm_SPHow		1
#define		M109_155mm_SPHow		2
#define		M107_175mm_SPHow		3
#define		M110_203mm_SPHow		4
#define		AT_5_Saxon_APC			5
#define		SSM_Lance_launcer		6
/*	Category_Towed_Artillery */			
#define		FH70_155mm_gun_towed		1
/*	Category_Small_WheeledUtilityVehicle */ 	
#define		LWB_LandRover			1
#define		LandRover_6by6_truck		2
/*	Category_LargeWheeledUtilityVehicle */	
/*	Category_SmallTrackedUtilityVehicle */	
/*	Category_LargeTrackedUtilityVehicle */	
/*	Category_Mortar */				

/* U.K. Air */
/* Category_Fighter */
#define		Tornado_ADV			1
#define		Lightning			2
#define		Phantom				3
/*	Category_Attack */				
#define		Sea_Harrier			1
#define		Harrier				2
#define		Bucaneer			3
#define		Tornado_GR1			4
#define		Jaguar_UK			5
#define		Hawk				6
/*	Category_Bomber */				
/*	Category_Cargo 	*/			
#define		K2_Victor			1
/*	Category_Anti-Sub/Patrol */		
#define		Nimrod_MK_R1			1
/*	Category_AttackHelicopter */		
/*	Category_UtilityHelicopter */		
#define		EH101_Merlin			1
#define		LynxHAS_2or3			2
#define		SeaKing_AEW2			3
#define		SeaKing_HAS5or6			4
#define		Gazelle_UK			5
#define		Puma_SuperPuma			6
#define		JetProvost			7
#define		Wessex				8
#define		Scout				9
#define		Wasp				10
#define		Beaver				11
#define		Chipmunk			12
#define		Auster				13
#define		AulouetteII			14
#define		JetStream			15
#define		BullDog				16

/* U.K. Surface */
/*	Category_Other */			
#define		Light_Aircraft_Carriers		1
#define		Type_82				2
#define		Type_42				3
#define		Class_Amazon			4
#define		Class_Broadsword		5
#define		Class_Duke			6
#define		Class_Leander			7
#define		Class_Hunt			8
#define		Class_River			9
#define		Class_Ton			10
#define		Class_Sandown			11

/* U.K. Subsurface */			
/*	Category_Other */
#define		Class_Vanguard_SSBN		1
#define		Class_Resolution_SSBN		2
#define		Class_W				3
#define		Class_Trafalger			4
#define		Class_Swiftsure			5
#define		Class_Valiant			6
#define		Class_Churchill			7
#define		Class_Upholder			8
#define		Class_Oberon			9
/* U.K. Space */
/*	Category_MannedPlatform */
/*	Category_UnmannedPlatform */
/* France Land */
/*	Category_Tank */
#define		AMX-30				1
#define			AMX_30B2	       		1
#define		AMX_13				2
/*	Category_ArmoredFightVeh */
#define		VBC90_ArmoredCar		1
#define		ERC90_ArmoredCar		2
#define		AML90_ArmoredCar		3
#define		AML60_ArmoredCar		4
#define		VAB_APC				5
#define		AMX10RC_ArmoredCar		6
#define		AMX13_IFV			7
#define		AMX10_IFV			8
#define		EBR_ArmoredCar			9
#define		AMX13_VCI_APC			10
#define		AMX13_DCA			11
#define		Berliet_VXB_ArmoredCar		12
#define		Panhard_EBR			13
/*	Category_ArmoredUtilVeh */	
#define		AMX10_ECH_RecoveryVehicle	1
/*	Category_SelfPropelArtillery */
#define		A_UF1_155mm_SPHow		1
#define		AMX_105mm_SPHow			2
#define		AU50_105mm_SPHow		3
#define		F3_155mm_SPGun			4
/*	Category_TowedArtillery */	
#define		TR_155mm_Howitzer		1
/*	Category_SmallWheelUtilVeh */
/*	Category_LargeWheelUtilVeh */
/*	Category_SmallTrackUtilVeh */
/*	Category_LargeTrackUtilVeh */
/*	Category_Mortar */
/* France Air */	
/*	Category_Fighter */
#define		MirageF1			1
#define		MirageII			2
#define		MirageIII			3
#define		MirageIV			4
#define		MirageV				5
#define		Mirage2000			6
#define		Gardian				7
#define		Mirage				8
/*	Category_Attack */
#define		Jaguar_France			1
#define		Etendard_IVP			2
#define		Super_Etendard			3
#define		AlphaJet2			4
/*	Category_Bomber */
/*	Category_Cargo */
#define		Transall			1
/*	Category_AntiSubPatrol */
#define		Atlantique			1
#define		Alize				2
/*	Category_AttackHelicopter */
/*	Category_UtilityHelicopter */
#define		AlouetteII_III			1
#define		SuperPuma_Puma			2
#define		Gazelle				3
#define		Lynx				4
#define		Panther				5
#define		Super_Frelon			6

/* France Surface */
/*	Category_Other */
#define		Class_Clemenceau		1
#define		Type_F70Destroyer		2
#define		Type_F70_AA			3
#define		Class_Suffren			4
#define		Type_F67			5
#define		Type_T56			6
#define		Type_T53			7
#define		Type_47				8
#define		Type_F65			9
#define		Class_FL3000_Frigate		10
#define		Type_Surveillance		11
#define		Type_CommanantRiviere		12
#define		Class_DEstienneDOrves_Type_A69	13
/*	Category_Carrier */
#define		NuclearPropelledAircraftCarrier	1
#define		HelicopterCarrier		2
#define	Category_Cruiser		50
/* France Subsurface */
/*	Category_Other */
#define		Class_LeTrionphant_SNLENG	1
#define		Class_LInflexible_SNLE		2
#define		Class_LeRedoutable_SNLE		3
#define		Class_Rubis_SNA72		4
#define		Class_Agosta			5
#define		Class_Daphne			6
#define		Class_Narval			7
/* France Subsurface */
/*	Category_Other */
#define	Category_MannedPlatform			1
#define	Category_UnmannedPlatform		2
/*	Germany	*/
		
/*	Category_Tank */			
#define			Leopard_1_A5Mbt		1                   
#define		Class_Tank			
#define			Leopard_1_A5MBT		1
#define                 Leopard_2_MBT			2
#define			LEOPARD_2_(Improved)BMT	
/*	Category_ArmoredFightingVehicle	*/
#define			Marder_1A3			1
#define			marder_2			2
#define			Bmp_1				3
#define			Jarguar_1TankDestoryer	4
#define			Jarguar_2			5
#define			LuchsArmoredReconnaissance	6
#define			ZobelArmoredreconnaissance	7
#define			RoandAirDefenceSystemMIS	8
#define			GepardArmoredAirDefenceGun	9
/*	Category_ArmoredUtilityVehicle */	
#define			BiberArmoredBridgelayer	1
#define			DachsArmoredEngineerTank	2
#define			KeilerArmoredMineSweeper	3
#define			SkorpionArmoredMineLayer	4
#define			M113ArmoredArtilleryObserver	7
#define			M113ArmoredMotorAmbulance	6
/*	Category_Mortar	*/			
/*	Category_M113_ArmoredMotar */		

/*      Category_Fighter */
#define 		MRCATornado			1
/*	Category_AttackHelocopter */
#define 		PAH1				1
#define			PAH2				2 
/************************** Munitions *****************/

/* U.S. Munition */

#define Category_AntiAir		1
#define		Class_Guided			1
#define			Sidewinder			1
#define			AMRAAM				2
#define			ADSM				3
#define			Falcon				4
#define			Chaparral			5
#define			Hawk_MIM23B			6
#define			MLMS				7
#define			Phoenix				8
#define			RapierUK			9
#define			Redeye				10
#define			Roland_US			11
#define			SeaSparrow			12
#define			Sparrow				13
#define			RIM66_RIM67			14
#define			Stinger				15
#define			Patriot_MIM104			16
#define			Tartar				17
#define			Terrier				18
#define			ADATS				19
#define	Category_AntiArmor		2
/*		Class_Guided */
#define			TOW				1
#define			M47_Dragon			2
#define			Hellfire			3
#define			Maverick			4
#define			Copperhead			5
#define			AAWS_M				6
#define	Category_AntiGuidedMunition	3
/*		Class_Guided */
#define			Decoys				1
#define	Category_AntiRadar		4
/*		Class_Guided */
#define			Harm_AGM88A			1
#define			Shrike_AGM45			2
#define			Standard_AGM78			3
#define			Sidearm_AGM122			4
#define			TACIT_RAINBOW			5
#define	Category_AntiSatellite		5
/*		Class_Guided */
#define			Asat				1
#define	Category_AntiShip		6
/*		Class_Guided */
#define			Harpoon_ARM_RGM_84A		1
#define			Harpoon_ARM_RGM_84B		2
#define			Harpoon_ARM_RGM_84C		3
#define			Harpoon_ARM_RGM_84D		4
#define			MK37E_TorpedoAntiShip		5
#define			MK48_Torpedo			6
#define			MK50_Torpedo			7
#define			Deadeye				8
#define			Penguin				9
#define	Category_AntiSubmarine		7
/*		Class_Guided */
#define			Mk46_Torpedo			1
#define			Mk48_Torpedo			2
#define			M50_Torpedo			3
#define			MK37E_TorpedoAntiSub		4
#define			ASROC_RUR5A			5
#define			CASW_SOW			6
#define			Subroc_UUM44A			7
#define E_Category_AntiPersonnel		8
#define	Cagetory_BattlefieldSupport	9
/*		Class_Guided */
#define			ALCM_AGM86B_BS			1
#define			Bullpup				2
#define			Lance_MGM52C			3
#define			Pershing_MGM31			4
#define			Tomahawk_AGM109_BS		5
#define			Tomahwlk_BGM109G		6
#define			Walleye_AGM62			7
#define			SRAM_AGM69			8
#define	E_Category_Strategic		10
/*		Class_Guided */
#define			MinutemanII_LGM30		1
#define			MinutemanIII			2
#define			Poseidon_UGM73			3
#define			TitanII_LGM25C			4
#define			TridentII_UGM93A		5
#define			Tomahawk_BGM109A		6
#define			Tomahawk_AGM109			7
#define			Tomahawk_BGM109G		8
#define			ALCM_AGM86B			9
#define			PeaceKeeper_MGM118		10
#define	Cagetory_Miscellaneous		11
/*		Class_Guided */
#define			Deadeye5inProjectile		1
#define Category_Bomb			12
/*        Class_Guided */
#define			MK82				1
#define        		MK84				2
/* Soviet  Munitions */
#define	Category_AntiAir		1
/*		Class_Guided */
#define			AA_1_Alkali			1
#define			AA_2_Atoll			2
#define			AA_3_Anab			3
#define			AA_4_Awl			4
#define			AA_5_Ash			5
#define			AA_6_Acrid			6
#define			AA_7_Apex			7
#define			AA_8_Aphid			8
#define			AA_9_Amos			9
#define			AA_10_Alamo			10
#define			AA_11_Archer			11
#define			SA_1_Guild			12
#define			SA_2_Guideline			13
#define			SA_3_GOA			14
#define			SA_4_Ganef			15
#define			SA_5_Gammon			16
#define			SA_6_Gainful			17
#define			SA_7_Grail			18
#define			SA_8_Gecko			19
#define			SA_9_Gaskin			20
#define			SA_10_Grumble			21
#define			SA_11_Gadfly			22
#define			SA_12_Gladiator_Giant		23
#define			SA_13_Gopher			24
#define			SA_14_Gremlin			25
#define			SA_15				26
#define			SA_16_man_portable_sam		27
#define			SA_N_1_GOA			28
#define			SA_N_2_Guideline		29
#define			SA_N_3_Goblet			30
#define			SA_N_4				31
#define			SA_N_5				32
#define			SA_N_6				33
#define			SA_N_7				34
#define			SA_N_9				35
#define	Category_Antiarmor		2
/*		Class_Guided */
#define			RPG_7VAT_Rocket_Launcher	1
#define			AS_8				2
#define			AT_1_Snapper			3
#define			AT_2_Swatter_Missile		4
#define			AT_3_Sagger_Missil_Guided	5
#define			AT_4_Spigot_Missile_Guided	6
#define			AT_5_Spandrel_Missile		7
#define			AT_6_Spiral_Missile		8
#define			AT_7_Saxhorn_Missile_Guided	9
#define			AT_8_Songster_Missile		10
#define			RPG_16				11
#define	Category_AntiGuidedMunition	3
/*		Class_Guided */
#define			ABM_1B				1
#define			SH_08				2
#define			Decoys_TBD			3
#define	Category_AntiRadar		4
/*		Class_Guided */
#define			AS_4_Kitchen_AntiRadar		1
#define			AS_9       			2
#define			AS_12_Kegler			3
/*	Category_AntiShip */
/*		Class_Guided */
#define			AS_2_Kipper			1
#define			AS_4_Kitchen_AntiShip		2
#define			AS_5_Kitchen			3
#define			AS_6_Kingfish			4
#define			AS_13				5
#define			AS_14_Kedge_AntiShip		6
#define			AS_15_Antiship			7
#define			SS_N_2_Styx			8
#define			SS_N_7_Starbright		9
#define			SS_N_9_Siren			10
#define			SS_N_12_Sandbox			11
#define			SS_N_19_Shipwreck		12
#define			SS_N_22_Sunburn			13
#define			SS_N_3_Shaddock			14
#define			SSC_2B_Samlet_Cruise		15
#define			SSC_1B_Sepal			16
#define			Torpedo_533mm_AntiShip		17
#define			Torpedo_406mm_AntiShip		18
#define			Torpedo_660mm_AntiShip		19
#define	Category_AntiSubmarine		7
/*		Class_Guided */
#define			FRAS_1				1
#define			SSN_14_Silex			2
#define			SSN_15_Starfish			3
#define			SSN_16_Stallion			4
#define			Torpedo_533mm_AntiSub		5
#define			Torpedo_406mm_AntiSub		6
#define			Torpedo_660mm_AntiSub		7
#define	Category_BattlefieldSupport	8
/*		Class_Guided */
#define			AS_3_Kangaroo			1
#define			AS_4_Kitchen			2
#define			AS_5_Kelt			3
#define			AS_7_Kerry			4
#define			AS_10_Karen			5
#define			AS_11_Kilter			6
#define			AS_14_Kedge_BS			7
#define			AS_15_Kent			8
#define			AS_X_10				9
#define			SS_1				10
#define			SS_12				11
#define			SS_21				12
#define			SS_22				13
#define			SS_23				14
#define Category_Strategic		9
/*		Class_Guided */
#define			SS_N_5				1
#define			SS_N_6				2
#define			SS_N_8				3
#define			SS_N_17				4
#define			SS_N_18				5
#define			SS_N_20				6
#define			SS_N_23				7
#define			SS_N_21     			8
#define			SS_NX_24     			9
#define			SSC_X_4				10
#define			AS_15_Strategic			11
#define			AS_16				12
#define			SS_4				13
#define			SS_11				14
#define			SS_13				15
#define			SS_16				16
#define			SS_17				17
#define			SS_18				18
#define			SS_19				19
#define			SS_20				20
#define			SS_24				21
#define			SS_25				22
#define Category_Miscellaneous		10
/* British Munition */
#define	Category_AntiAir		1
/*		Class_Guided */
#define			Bloodhound_Mk2			1
#define			Rapier				2
#define			Seacat_Tigercat			3
#define			Blowpipe_Guided			4
#define			Javelin_Guided			5
#define			Star_Streak			6
#define			Sea_Dart			7
#define			Sea_Wolf			8
#define			Sky_Flash			9
#define			Fire_Streak			10
#define			Red_Top				11
#define	Category_AntiArmor		2
/*		Class_Guided */
#define			Milan_missile			1
#define			Swingfire_missile		2
#define			Merlin				3
#define			FI_TOW				4
#define			Vigilant_missile		5
#define			Hot_missile			6
#define	Category_AntiGuidedMunition	3
/*		Class_Guided */
#define			Decoys				1
#define	Category_AntiRadar		4
/*		Class_Guided */
#define			Alarm				1
/*	Category_AntiShip */
/*		Class_Guided */
#define			Excalibur			1
#define			Sea_Eagle			2
#define			Sea_Skua			3
#define			Martel				4
#define			Spear_fish_Torpedo		5
#define	Category_AntiSubmarine		7
/*		Class_Guided */
#define			Tigerfish_Torpedo		1
#define			Spear_Fish_Torpedo		2
#define			Sting_Ray_Torpedo		3
#define			Mk_24_Torpedo			4
#define	Category_BattlefieldSupport	8
/*		Class_Guided */
#define			Lance				1
#define Category_Strategic		9
#define Category_Miscellaneous		10
/* French Munition */
/*	Category_AntiAir */
/*		Class_Guided */
#define			Aster_15			1
#define			Aster_30			2
#define			Crotale				3
#define			Roland_France			4
#define			Mistral				5
#define			Masurca				6
#define			Mica_Missile			7
#define			R_530_Sidewinder		8
#define			R_550_Magic			9
#define			Super_530			10
#define	Category_AntiArmor		2
/*		Class_Guided */
#define			SS11				1
#define			Eryx_Missile			2
#define			HOT_Missile			3
#define			Milan_Missile			4
#define			ACL_STRIM			5
#define			Entac				6
#define	Category_AntiGuidedMunition	3
/*		Class_Guided */
#define			Decoys				1
#define	Category_AntiRadar		4
/*		Class_Guided */
#define			Armat				1
/*	Category_AntiShip */
/*		Class_Guided */
#define			Exocet				1
#define			AS_11				2
#define			AS_12				3
#define			AS_15_Guided			4
#define			AS_30				5
#define			AS_37_Martel			6
#define			ASMP				7
#define			Otomat				8
#define			E_14_GuidedTorpedo		9
#define			E_15_GuidedTorpedo		10
#define			F_17_GuidedTorpedo		11
#define			L_5_GuidedTorpedo		12
#define			Z_16_GuidedTorpedo		13
#define	Category_AntiSubmarine		7
/*		Class_Guided */
#define			Malafon				1
#define			E_14_Torpedo			2
#define			E_15_Torpedo			3
#define			F_17_Torpedo			4
#define			L3_Torpedo			5
#define			L4_Torpedo			6
#define			L5_Torpedo			7
#define			Murene_Torpedo			8
#define	Category_BattlefieldSupport	8
/*		Class_Guided */
#define			Hades_Missile			1
#define			Pluton_Missile			2
#define	Category_Strategic		9
/*		Class_Guided */
#define			SSBS_Type_S_30D_TN_61		1
#define			SSBS_Type_S_4_SX		2
#define			SLBM_M_20			3
#define			SLBM_M_4			4
#define Category_Miscellaneous		10
/* U.S. Ballistic Munitions */
/*	Germany	Munition */
#define Category_AntiAir			1
#define		Class_Guided			1
#define			Roland				1
#define Category_AntiArmor		2
#define        Class_Guided			1
#define               	MilanMissile			1
#define 		Hot_Missile			2
#define			Tow_Missile			3
#define			Pars3_Missile			4
/* Category_BattlefieldSupport */
#define       Class_Guided			1
#define 		ParachuteSignalRocketWhite	1
#define Category_AntiArmor 
#define		Class_Ballistic			2
#define			mm25				1
#define			mm84				2
#define			E_mm105				3
#define			E_mm120				4
#define			mm155				5
#define			mm227				6
#define E2_Category_AntiPersonnel			
#define		Class_Ballistic			2
#define			mm5_56				1 /* Note: #defines */
#define			mm7_62				2 /* must not start */
#define			mm9_0				3 /* with digits */
#define			mm11_43				4
#define			mm12_7				5
/*	Category_BattlefieldSupport */
/*		Class_Ballistic */
#define			mm20_ballistic			1
#define			mm25_ballistic			2
#define			mm30_ballistic			3
#define			mm40_ballistic			4
#define			mm60_ballistic			5
#define			mm66_ballistic			6
#define			mm76_ballistic			7
#define			mm81_ballistic			8
#define			mm90_ballistic			9
#define			mm105_ballistic			10
#define			mm120_ballistic			11
#define			mm127_ballistic			12
#define			mm152_ballistic			13
#define			mm155_ballistic			14
#define			mm203_ballistic			15
#define			mm227_rocket			16
#define			mm406_ballistic			17
#define			mm107_ballistic			18
/*      Category_Bomb  */		
/*	Class_Ballistic	 */
#define			CBU_15				1
#define			CBU_52				2	
#define			CBU_58				3
#define			CBU_71				4
#define			CBU_87				5
#define			CBU_89				6
#define			MK_81				7
#define			MK_82				8
#define			MK_83				9
#define			MK_84				10
#define			BLU				11
#define			MK_20				12
#define			Durandal			13	     			
/* Soviet Ballistic Munitions */
#define	Category_AntiAmor		2
/*             Class_Ballistic	*/
#define			mm23				1
#define			mm30				2
#define			mm73				3
#define			mm76				4
#define			mm85				5
#define			mm115				6
#define			mm125				7
#define			mm135				8			
#define	Category_AntiPersonnel		1
/*		Class_Ballistic */
#define			mm5_45_ballistic		1
#define			mm7_62_ballistic		2
#define			mm12_7_ballistic		3
#define			mm14_5_ballistic		4		3
/*	Category_BattlefieldSupport */
/*		Class_Ballistic */
#define			mm14_5				1
#define			E_mm23				2
#define			E_mm25				3
#define			E_mm30				4
#define			mm37				5
#define			mm40_rocket			6
#define			mm45				7
#define			mm57				8
#define			E_mm73				9
#define			E_mm76				10
#define			mm82				11
#define			E_mm85				12
#define			mm100				13
#define			E_mm115				14
#define			mm120				15
#define			mm122				16
#define			mm122_rocket			17
#define			E_mm125				18
#define			mm130				19
#define			mm152				20
#define			mm160				21
#define			mm180				22
#define			mm240				23
#define			mm240_rocket			24
#define			mm250_rocket			25
#define			mm400_rocket			26
#define			mm550_rocket			27
#define			mm600_rocket			28
#define			mm850_missile			29
#define			mm1100_missile			30
#define			mm203_Howitzer			31
#define			mm220_Rocket			32
/* British Ballistic Munitions */
#define	Category_AntiPersonnel		1
/*		Class_Ballistic */
#define			mm7_62_ballistic_UK		1
#define			mm9_0_ballistic_UK		2
/*	Category_BattlefieldSupport */
/*		Class_Ballistic */
#define			mm51_ballistic_UK		1
#define			mm89_ballistic_UK		2
#define			mm105_ballistic_UK		3
#define			mm155_ballistic_UK		4
#define			mm175_ballistic_UK		5

/* French Ballistic Munitions */
/*	Category_BattlefieldSupport */
/*		Class_Ballistic */
#define			mm58_ballistic_France		1
#define			mm105_ballistic_France		2
#define			mm155_ballistic_France		3
/* Germany Munitions */
/*	Category_AntiArmor */		
/*	Class_Ballistic	*/		
#define			mm110_Rocket_Germany		1			1
/*	Category_AntiPersonnel*/	
#define		Ballistic			2
#define			mm5.56				1
#define			mm7.62				2
#define			mm9				3
/*	Category_BattlefieldSupport */	
#define		Ballistic			2
#define			mm20				1
#define			mm35				2
#define			mm73				3
#define			mm105				4
#define			mm120
/* U.S. Munitions */
#define	Category_Antipersonnel		1
#define		Class_Fixed			3
#define			M16_mine			1
#define			Claymore_mine			2
#define			Heavy_M15_AT_mine		3
#define			Nonmetallic_M19_AT_mine		4
#define			Heavy_M21_AT_mine		5
#define			Scatterable_M741_AT_mine	6
#define			Scatterable_M718_AT_mine	7
#define			Scatterable_M75_AT_mine		8
#define			Nonmetallic_M14_ToePopper_AP
#define			mine				9
#define			Scatterable_M731_AP_mine	10
#define			Scatterable_M692_AP_mine	11
#define			Scatterable_M74_AP_mine		12

/* U.S.S.R. Munitions */
#define	Category_AntiPersonnel		1
#define		Class_Fixed			3
#define			Wooden_TMD_B_AT_mine		1
#define			Wooden_YAM_5_AT_mine		2
#define			TM_38_AT_mine			3
#define			TM_44_AT_mine			4
#define			TM_46_AT_Blast_mine		5
#define			TMN_46_AT_Blast_mine		6
#define			TM_57_AT_mine			7
#define			TM_62M_mine			8
#define			TMK_2_AT_shaped_charge_mine	9
#define			Area_type_POMZ_2_AP_Frag_mine	10
#define			OMZ_3_AP_Frag_mine		11
#define			MON_series_AP_mine		12
#define			PMN_AP_Blast_mine		13
#define			PMK_40_AP_Blast_mine		14

/* U.S. Life Forms Weapons */
#define		Redeye_FIM_43A				1
#define		Dragon_M47_FGM_77A			2
#define		Stinger_FIM_92A				3
#define		M72_Light_Antitank_Weapon_LAW_II	4
#define		Mk_193_83mm_SMAW			5
#define		M60_General_Purpose_Machine_Gun		6
#define		M2_HB_Heavy_Machine_Gun			7
#define		M67_Recoilless_Rifle			8
#define		M_203_Grenade_Launcher			9
#define		M16A1_Rifle				10
#define		M9_Pistol				11
#define		M1911A1_Pistol				12
#define		M249_SAW 				13

/* Soviet Life Forms Weapons */
#define		SA_7_Grail_Missile			1
#define		RPG_7_VAT_Rocket_Launcher		2
#define		RPG_18					3
#define		AT_4_Spigot_Missile			4
#define		AT_3_Sagger_Missile			5
#define		AT_7_Saxhorn_Missile			5
#define		PK_GPMG_7_62mm				6
#define		RPK_GPMG_7_62mm				7
#define		AK_and_AKM_Assault_Rifles_7_62mm	8
#define		AKS_74_Assault_Rifle_5_45mm		9
#define		SVD_Sniper_Rifle_7_62mm			10
#define		RKG_3M_AT_Hand_Grenade			11
#define		RGD_5_Hand_Grenade			12
#define		AGS_17_Plamya_Grenade_Launcher		13

/* British Life Forms Weapons */
#define		LAW_80					1
#define		Blowpipe				2
#define		Javelin					3
#define		Mortar_51mm				4
#define		SLR_7_62mm_Rifle			5
#define		Sterling_9mm_Rifle			6
#define		L7A2_General_Purpose_Machine_Gun	7
#define		L6_Wombat_Recoilless_rifle		8
#define		Carl_Gustav_89mm_Recoilless_rifle	9
#define		SA80_Indiv_wpn_light_support_wpn	10
#define		Trigat					11
#define		Milan_AT_missile			12
/* French Life Forms Weapons */
#define		ACL_Strim				1
#define		Mistral_Missile				2
#define		Milan_AT_Missile			3
#define		LRAC_F1_89mm_AT_rocket_launcher		4
#define		FA_MAS_rifle				5
#define		AA_52_machine_gun			6
#define		Rifle_Grenade_58mm			7
#define		FR_F1_Sniper_rifle			8

/* EOF */
