# ***** ALWAYS leave the following include line ***
include ../../Makefile.lib_pre

MAKEFILE	=	Makefile

# You can change these flags while testing for optimizations
#OPT	=	-O2
#CFLAGS	=	$(OPT)

# You can locally define any symbols you need using the next line
#DEFINES	=

# You can define include directories your code needs here --
#    other than ../include
APPINCDIRS	=	-I../../apps/include -I../../c2/include \
	-I../../communication/include -I../../database/include \
	-I../../display/include -I../../entities/include \
	-I../../environment/include -I../../interface/include \
	-I../../media/include -I../../setup/include -I../../utilities/include \
	-I$(JACKML_INCDIR) -I$(IPORT_INCDIR) -I$(MCAST_INCDIR) \
	-I/usr/include/Performer -I/usr/src/Performer/include

# ***********************************************************************
# ***** ALWAYS list targets and the objects for the targets here *****

SOURCES	=	ground_veh.cc
TARGETS =       $(LIBDIR)libgroundveh$(GL_EXT)$(BIN_EXT).$(LIB_EXT)
OBJECTS	=	ground_veh$(GL_EXT)$(BIN_EXT).o

# ***********************************************************************


# ***** ALWAYS leave the following include line ***
include ../../Makefile.lib_post


# ***********************************************************************
# DO NOT DELETE THIS LINE -- make depend depends on it.

ground_veh$(GL_EXT)$(BIN_EXT).o: ../include/ground_veh.h ../include/vehicle.h
ground_veh$(GL_EXT)$(BIN_EXT).o: ../include/entity_const.h
ground_veh$(GL_EXT)$(BIN_EXT).o: ../../utilities/include/conversion_const.h ../include/weapon.h
ground_veh$(GL_EXT)$(BIN_EXT).o: /usr/include/Performer/pf.h ../../communication/include/pdu.h
ground_veh$(GL_EXT)$(BIN_EXT).o: ../../communication/include/envirvalues.h
ground_veh$(GL_EXT)$(BIN_EXT).o: ../../communication/include/identify.h
ground_veh$(GL_EXT)$(BIN_EXT).o: ../../display/include/draw.h
ground_veh$(GL_EXT)$(BIN_EXT).o: ../../display/include/display_types.h
ground_veh$(GL_EXT)$(BIN_EXT).o: ../../apps/include/common_defs.h
ground_veh$(GL_EXT)$(BIN_EXT).o: ../../communication/include/rwstruct.h
ground_veh$(GL_EXT)$(BIN_EXT).o: ../../setup/include/setup_const.h
ground_veh$(GL_EXT)$(BIN_EXT).o: ../../display/include/display_const.h
ground_veh$(GL_EXT)$(BIN_EXT).o: ../../interface/include/nps_device.h
ground_veh$(GL_EXT)$(BIN_EXT).o: /usr/include/Performer/pfutil.h ../../c2/include/highlight.h
ground_veh$(GL_EXT)$(BIN_EXT).o: ../../c2/include/c2_const.h ../../display/include/XCursorUtil.h
ground_veh$(GL_EXT)$(BIN_EXT).o: ../../interface/include/hmdClass.h /usr/include/Performer/pr.h
ground_veh$(GL_EXT)$(BIN_EXT).o: /usr/include/Performer/opengl.h
ground_veh$(GL_EXT)$(BIN_EXT).o: ../../interface/include/FastrakClass.h
ground_veh$(GL_EXT)$(BIN_EXT).o: ../../interface/include/fakespaceClass.h
ground_veh$(GL_EXT)$(BIN_EXT).o: ../../interface/include/input_device.h
ground_veh$(GL_EXT)$(BIN_EXT).o: ../../interface/include/lw_tcpip.h
ground_veh$(GL_EXT)$(BIN_EXT).o: ../../communication/include/ip_co_sockcomm.h
ground_veh$(GL_EXT)$(BIN_EXT).o: ../../communication/include/ip_sockcomm.h
ground_veh$(GL_EXT)$(BIN_EXT).o: ../../communication/include/sockcomm.h
ground_veh$(GL_EXT)$(BIN_EXT).o: ../../communication/include/co_sockcomm.h
ground_veh$(GL_EXT)$(BIN_EXT).o: ../../interface/include/lw-nps.h
ground_veh$(GL_EXT)$(BIN_EXT).o: ../../interface/include/input_manager.h
ground_veh$(GL_EXT)$(BIN_EXT).o: ../../utilities/include/automateClass.h
ground_veh$(GL_EXT)$(BIN_EXT).o: ../../utilities/include/infoClass.h
ground_veh$(GL_EXT)$(BIN_EXT).o: ../../apps/include/common_defs2.h
ground_veh$(GL_EXT)$(BIN_EXT).o: ../../apps/include/constants.h ../../apps/include/macros.h
ground_veh$(GL_EXT)$(BIN_EXT).o: ../../database/include/terrain.h ../../media/include/sound.h
ground_veh$(GL_EXT)$(BIN_EXT).o: ../../communication/include/disnetlib.h
ground_veh$(GL_EXT)$(BIN_EXT).o: ../../communication/include/netutil.h
ground_veh$(GL_EXT)$(BIN_EXT).o: ../../display/include/effects.h ../include/entity.h
ground_veh$(GL_EXT)$(BIN_EXT).o: ../include/munitions.h ../../communication/include/appearance.h
ground_veh$(GL_EXT)$(BIN_EXT).o: ../../interface/include/interface_const.h
ground_veh$(GL_EXT)$(BIN_EXT).o: ../../communication/include/local_snd_code.h
ground_veh$(GL_EXT)$(BIN_EXT).o: ../include/collision_const.h
ground_veh$(GL_EXT)$(BIN_EXT).o: ../../communication/include/articulat.h
