CXX	=	CC
CC	=	cc

LIB_TARGET = ../../../bin/lib/

NOFLAGS		=	-DNODUDE -DNO_DVW -DNOS1kLOADER -DNONPSSHIP \
			-DNOC2MEASURES -DNOAHA $(BUG_FIX)
JACKML_INCDIR	=	../../../otherlibs/Jack/JackML
IPORT_INCDIR	=	../../../otherlibs/ISMS
MCAST_INCDIR	=	../../../otherlibs/ISMS/Mcast
JACKML_LIBDIR	=	../../../otherlibs/Jack/JackML
IPORT_LIBDIR	=	../../../otherlibs/ISMS
MCAST_LIBDIR	=	../../../otherlibs/ISMS/Mcast
